// Generated by Framer (835d061)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  getWhereExpressionFromPathVariables,
  Image as Image1,
  NotFoundError,
  PropertyOverrides,
  queryCache,
  RichText,
  runTasksWithYield,
  useComponentViewport,
  useCurrentPathVariables,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  useRouteElementId,
  useSiteRefs,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import SectionTag from "#framer/local/canvasComponent/F2GdECUJ5/F2GdECUJ5.js";
import FAQSection from "#framer/local/canvasComponent/S8ygGzZl3/S8ygGzZl3.js";
import Legal from "#framer/local/collection/BqdJRSU4x/BqdJRSU4x.js";
import * as sharedStyle1 from "#framer/local/css/BczsPivWE/BczsPivWE.js";
import * as sharedStyle2 from "#framer/local/css/Gb9Urlcot/Gb9Urlcot.js";
import * as sharedStyle from "#framer/local/css/MVvA5iU4p/MVvA5iU4p.js";
import metadataProvider from "#framer/local/webPageMetadata/CdkisGZLh/CdkisGZLh.js";
const SectionTagFonts = getFonts(SectionTag);
const FAQSectionFonts = getFonts(FAQSection);
const breakpoints = {
  HDbx3MLOK: "(max-width: 809.98px)",
  nI2FWDVpP: "(min-width: 1200px)",
  Sme79T7hW: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-iKZEP";
const variantClassNames = {
  HDbx3MLOK: "framer-v-1mabl40",
  nI2FWDVpP: "framer-v-yfl04y",
  Sme79T7hW: "framer-v-36o511",
};
const zoTxNZgx7 = undefined;
const fGKLm7rBJ = undefined;
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "nI2FWDVpP",
  Phone: "HDbx3MLOK",
  Tablet: "Sme79T7hW",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const detailQuery = (where) => ({
  from: { alias: "CdkisGZLh", data: Legal, type: "Collection" },
  select: [
    { collection: "CdkisGZLh", name: "zoTxNZgx7", type: "Identifier" },
    { collection: "CdkisGZLh", name: "fGKLm7rBJ", type: "Identifier" },
  ],
  where,
});
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "nI2FWDVpP",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const currentPathVariables = useCurrentPathVariables();
  const [currentRouteData] = useQueryData(
    detailQuery(
      getWhereExpressionFromPathVariables(currentPathVariables, "CdkisGZLh")
    )
  );
  const getFromCurrentRouteData = (key) => {
    if (!currentRouteData)
      throw new NotFoundError(
        `No data matches path variables: ${JSON.stringify(
          currentPathVariables
        )}`
      );
    return currentRouteData[key];
  };
  const {
    style,
    className,
    layoutId,
    variant,
    zoTxNZgx7 = getFromCurrentRouteData("zoTxNZgx7") ?? "",
    fGKLm7rBJ = getFromCurrentRouteData("fGKLm7rBJ") ?? "",
    ...restProps
  } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({ zoTxNZgx7 }, activeLocale),
    [zoTxNZgx7, activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const elementId = useRouteElementId("g1iOqbQ7u");
  const dynamicRef = useSiteRefs();
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "nI2FWDVpP",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-yfl04y", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-az96hn",
              "data-framer-name": "Hero Section",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsx(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 1032,
                    intrinsicWidth: 1600,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0 + 0
                    ),
                    pixelHeight: 1032,
                    pixelWidth: 1600,
                    sizes: componentViewport?.width || "100vw",
                    src: "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032",
                    srcSet:
                      "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=512&width=1600&height=1032 512w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=1024&width=1600&height=1032 1024w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032 1600w",
                  },
                  className: "framer-mvqrp5",
                  "data-framer-name": "BG",
                }),
                /*#__PURE__*/ _jsx("div", { className: "framer-rdmy95" }),
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-7i05hl",
                  "data-framer-name": "Container",
                  children: /*#__PURE__*/ _jsxs("div", {
                    className: "framer-2k29mn",
                    "data-framer-name": "Header Content",
                    id: elementId,
                    ref: dynamicRef(elementId),
                    children: [
                      /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          HDbx3MLOK: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              150 +
                              0 +
                              0 +
                              0 +
                              0 +
                              0,
                          },
                          Sme79T7hW: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              150 +
                              0 +
                              0 +
                              0 +
                              0,
                          },
                        },
                        children: /*#__PURE__*/ _jsx(
                          ComponentViewportProvider,
                          {
                            height: 47,
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              210 +
                              0 +
                              0 +
                              0 +
                              0,
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-1dnscpm-container",
                              nodeId: "v7vzR9OdU",
                              scopeId: "CdkisGZLh",
                              children: /*#__PURE__*/ _jsx(SectionTag, {
                                height: "100%",
                                id: "v7vzR9OdU",
                                j9h2sFaQp: "Privacy Policy",
                                layoutId: "v7vzR9OdU",
                                qbRh5Zv2v:
                                  "var(--token-73b66216-b475-415b-b4b6-227679c18659, rgb(195, 230, 255))",
                                width: "100%",
                              }),
                            }),
                          }
                        ),
                      }),
                      /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          HDbx3MLOK: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("h2", {
                                className: "framer-styles-preset-b4fewl",
                                "data-styles-preset": "MVvA5iU4p",
                                dir: "auto",
                                style: {
                                  "--framer-text-alignment": "start",
                                  "--framer-text-color":
                                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                },
                                children: "How We Protect Data",
                              }),
                            }),
                          },
                        },
                        children: /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h2", {
                              className: "framer-styles-preset-b4fewl",
                              "data-styles-preset": "MVvA5iU4p",
                              dir: "auto",
                              style: {
                                "--framer-text-color":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              },
                              children: "How We Protect Data",
                            }),
                          }),
                          className: "framer-1c7nzya",
                          "data-framer-name": "Header Title",
                          fonts: ["Inter"],
                          text: zoTxNZgx7,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      }),
                    ],
                  }),
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-y2vk6k",
              "data-framer-name": "Privacy Section",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsx("div", {
                className: "framer-1jwy7d1",
                "data-framer-name": "Container",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: fGKLm7rBJ,
                  className: "framer-8qbrsj",
                  "data-framer-name": "Section Title",
                  fonts: ["Inter"],
                  stylesPresetsClassNames: {
                    h3: "framer-styles-preset-176ky7y",
                    p: "framer-styles-preset-7k06ux",
                  },
                  verticalAlignment: "center",
                  withExternalLayout: true,
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(PropertyOverrides, {
              breakpoint: baseVariant,
              overrides: {
                HDbx3MLOK: { y: (componentViewport?.y || 0) + 0 + 460.2 },
                Sme79T7hW: { y: (componentViewport?.y || 0) + 0 + 480.2 },
              },
              children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 1216,
                width: componentViewport?.width || "100vw",
                y: (componentViewport?.y || 0) + 0 + 580.2,
                children: /*#__PURE__*/ _jsx(Container, {
                  className: "framer-1uiosuv-container",
                  layout: motionLayout,
                  nodeId: "IkWuRjUQo",
                  scopeId: "CdkisGZLh",
                  children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      HDbx3MLOK: { variant: matchVariant("t2zBn0xVU") },
                      Sme79T7hW: { variant: matchVariant("FCNMlRrs0") },
                    },
                    children: /*#__PURE__*/ _jsx(FAQSection, {
                      height: "100%",
                      id: "IkWuRjUQo",
                      layoutId: "IkWuRjUQo",
                      style: { width: "100%" },
                      variant: matchVariant("LQf0My7Ir"),
                      width: "100%",
                    }),
                  }),
                }),
              }),
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  ".framer-iKZEP.framer-6rredv, .framer-iKZEP .framer-6rredv { display: block; }",
  ".framer-iKZEP.framer-yfl04y { align-content: center; align-items: center; background-color: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, #faf9ff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-iKZEP .framer-az96hn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 210px 30px 120px 30px; position: relative; width: 100%; z-index: 1; }",
  ".framer-iKZEP .framer-mvqrp5 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; justify-content: center; left: 0px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-filter-override, filter); }",
  ".framer-iKZEP .framer-rdmy95 { background: linear-gradient(180deg, var(--token-b792d557-4853-49ac-865a-1d8073a4ab4e, rgba(174, 220, 253, 0.6)) 0%, rgba(250, 249, 255, 0) 100%); bottom: 0px; flex: none; gap: 40px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 100%; }",
  ".framer-iKZEP .framer-7i05hl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; max-width: 1296px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-iKZEP .framer-2k29mn { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-iKZEP .framer-1dnscpm-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-iKZEP .framer-1c7nzya { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-iKZEP .framer-y2vk6k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
  ".framer-iKZEP .framer-1jwy7d1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1296px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-iKZEP .framer-8qbrsj { --framer-paragraph-spacing: 24px; flex: none; height: auto; max-width: 1124px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-iKZEP .framer-1uiosuv-container { flex: none; height: auto; position: relative; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-iKZEP.framer-yfl04y { width: 810px; } .framer-iKZEP .framer-az96hn { padding: 150px 30px 80px 30px; }}",
  "@media (max-width: 809.98px) { .framer-iKZEP.framer-yfl04y { width: 390px; } .framer-iKZEP .framer-az96hn { gap: 40px; padding: 150px 20px 60px 20px; } .framer-iKZEP .framer-7i05hl { align-content: center; align-items: center; flex-direction: column; gap: 32px; justify-content: center; } .framer-iKZEP .framer-2k29mn { flex: none; justify-content: center; width: 100%; } .framer-iKZEP .framer-y2vk6k { padding: 0px 20px 0px 20px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 5621
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Sme79T7hW":{"layout":["fixed","auto"]},"HDbx3MLOK":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"g1iOqbQ7u":{"pattern":":g1iOqbQ7u","name":"nav"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerCdkisGZLh = withCSS(Component, css, "framer-iKZEP");
export default FramerCdkisGZLh;
FramerCdkisGZLh.displayName = "Legal";
FramerCdkisGZLh.defaultProps = { height: 5621, width: 1200 };
addFonts(
  FramerCdkisGZLh,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...SectionTagFonts,
    ...FAQSectionFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerCdkisGZLh.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const priority = context.priority;
    return runTasksWithYield(
      [
        () =>
          queryCache
            .get(
              detailQuery(
                getWhereExpressionFromPathVariables(
                  context.pathVariables,
                  "CdkisGZLh"
                )
              ),
              locale,
              priority
            )
            .preload(),
        () => forwardLoader(SectionTag, {}, context),
        () => forwardLoader(FAQSection, {}, context),
      ],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerCdkisGZLh",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "5621",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerResponsiveScreen: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Sme79T7hW":{"layout":["fixed","auto"]},"HDbx3MLOK":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1200",
        framerLayoutTemplateFlowEffect: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerAcceptsLayoutTemplate: "true",
        framerAutoSizeImages: "true",
        framerScrollSections:
          '{"g1iOqbQ7u":{"pattern":":g1iOqbQ7u","name":"nav"}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
