// Generated by Framer (0e6a859)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  PropertyOverrides,
  ResolveLinks,
  RichText,
  runTasksWithYield,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useRouteElementId,
  useRouter,
  useSiteRefs,
  withCSS,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Button from "#framer/local/canvasComponent/CapSjRnOK/CapSjRnOK.js";
import * as sharedStyle from "#framer/local/css/BczsPivWE/BczsPivWE.js";
import * as sharedStyle2 from "#framer/local/css/Gb9Urlcot/Gb9Urlcot.js";
import * as sharedStyle1 from "#framer/local/css/pW0axsC3J/pW0axsC3J.js";
import metadataProvider from "#framer/local/webPageMetadata/CzmevToMm/CzmevToMm.js";
const Image1WithOptimizedAppearEffect = withOptimizedAppearEffect(Image1);
const MotionDivWithOptimizedAppearEffect = withOptimizedAppearEffect(
  motion.div
);
const ButtonFonts = getFonts(Button);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const breakpoints = {
  aFsUc6yLS: "(min-width: 810px) and (max-width: 1199.98px)",
  K81AT5cri: "(min-width: 1200px)",
  YAGFqqlki: "(max-width: 809.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-bV7TU";
const variantClassNames = {
  aFsUc6yLS: "framer-v-1vhkl84",
  K81AT5cri: "framer-v-1sims9x",
  YAGFqqlki: "framer-v-1brvhnp",
};
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const transition1 = {
  delay: 0,
  duration: 1,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.9,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transition2 = {
  delay: 0.2,
  duration: 0.8,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation3 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 24,
};
const transition3 = {
  delay: 0.4,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation4 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition3,
  x: 0,
  y: 0,
};
const animation5 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 20,
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "K81AT5cri",
  Phone: "YAGFqqlki",
  Tablet: "aFsUc6yLS",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "K81AT5cri",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const elementId = useRouteElementId("iO9Sks8kp");
  const dynamicRef = useSiteRefs();
  const router = useRouter();
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "K81AT5cri",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255)); }",
        }),
        /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-1sims9x", className),
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-18vacpp",
            "data-framer-name": "Hero Section",
            layout: motionLayout,
            children: [
              /*#__PURE__*/ _jsx(Image1, {
                background: {
                  alt: "",
                  fit: "fill",
                  intrinsicHeight: 1032,
                  intrinsicWidth: 1600,
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 0 + 0 + 0
                  ),
                  pixelHeight: 1032,
                  pixelWidth: 1600,
                  sizes: componentViewport?.width || "100vw",
                  src: "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032",
                  srcSet:
                    "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=512&width=1600&height=1032 512w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=1024&width=1600&height=1032 1024w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032 1600w",
                },
                className: "framer-li7ewk",
                "data-framer-name": "BG",
              }),
              /*#__PURE__*/ _jsx("div", { className: "framer-1tz6r32" }),
              /*#__PURE__*/ _jsxs("div", {
                className: "framer-aa0hva",
                "data-framer-name": "Container",
                children: [
                  /*#__PURE__*/ _jsxs("div", {
                    className: "framer-1of4jbr",
                    "data-framer-name": "Content Wrapper",
                    id: elementId,
                    ref: dynamicRef(elementId),
                    children: [
                      /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          aFsUc6yLS: {
                            background: {
                              alt: "",
                              fit: "fill",
                              intrinsicHeight: 304,
                              intrinsicWidth: 723,
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  0 +
                                  0 +
                                  180 +
                                  0 +
                                  0 +
                                  0 +
                                  0 +
                                  0
                              ),
                              pixelHeight: 304,
                              pixelWidth: 723,
                              sizes: `min(${
                                componentViewport?.width || "100vw"
                              } - 60px, 723px)`,
                              src: "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304",
                              srcSet:
                                "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?scale-down-to=512&width=723&height=304 512w,https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304 723w",
                            },
                          },
                          YAGFqqlki: {
                            background: {
                              alt: "",
                              fit: "fill",
                              intrinsicHeight: 304,
                              intrinsicWidth: 723,
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  0 +
                                  0 +
                                  150 +
                                  0 +
                                  0 +
                                  0 +
                                  0 +
                                  0
                              ),
                              pixelHeight: 304,
                              pixelWidth: 723,
                              sizes: `min(${
                                componentViewport?.width || "100vw"
                              } - 40px, 723px)`,
                              src: "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304",
                              srcSet:
                                "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?scale-down-to=512&width=723&height=304 512w,https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304 723w",
                            },
                          },
                        },
                        children: /*#__PURE__*/ _jsx(
                          Image1WithOptimizedAppearEffect,
                          {
                            animate: animation,
                            background: {
                              alt: "",
                              fit: "fill",
                              intrinsicHeight: 304,
                              intrinsicWidth: 723,
                              loading: getLoadingLazyAtYPosition(
                                (componentViewport?.y || 0) +
                                  0 +
                                  0 +
                                  0 +
                                  241.8 +
                                  0 +
                                  0 +
                                  0 +
                                  0
                              ),
                              pixelHeight: 304,
                              pixelWidth: 723,
                              sizes: `min(${
                                componentViewport?.width || "100vw"
                              } - 60px, 723px)`,
                              src: "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304",
                              srcSet:
                                "https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?scale-down-to=512&width=723&height=304 512w,https://framerusercontent.com/images/V2aBs4HbzxRpJeAlO2HMykinNfQ.svg?width=723&height=304 723w",
                            },
                            className: "framer-crixkf",
                            "data-framer-appear-id": "crixkf",
                            fitImageDimension: "height",
                            initial: animation1,
                            optimized: true,
                          }
                        ),
                      }),
                      /*#__PURE__*/ _jsxs(MotionDivWithOptimizedAppearEffect, {
                        animate: animation2,
                        className: "framer-1qmqzj7",
                        "data-framer-appear-id": "1qmqzj7",
                        "data-framer-name": "Error Message Text Container",
                        initial: animation3,
                        optimized: true,
                        children: [
                          /*#__PURE__*/ _jsxs("div", {
                            className: "framer-8dyj8m",
                            "data-framer-name": "Title",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("h1", {
                                    className: "framer-styles-preset-176ky7y",
                                    "data-styles-preset": "BczsPivWE",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                    },
                                    children: "Opps!",
                                  }),
                                }),
                                className: "framer-rwtc7j",
                                "data-framer-name": "Error Title",
                                fonts: ["Inter"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("h1", {
                                    className: "framer-styles-preset-j82zyb",
                                    "data-styles-preset": "pW0axsC3J",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                    },
                                    children: /*#__PURE__*/ _jsx("em", {
                                      children: "Page Not",
                                    }),
                                  }),
                                }),
                                className: "framer-1maulwa",
                                "data-framer-name": "Error Title",
                                fonts: ["Inter", "Inter-Italic"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx("h1", {
                                    className: "framer-styles-preset-176ky7y",
                                    "data-styles-preset": "BczsPivWE",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                    },
                                    children: "Found!",
                                  }),
                                }),
                                className: "framer-hwgd5e",
                                "data-framer-name": "Error Title",
                                fonts: ["Inter"],
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-7k06ux",
                                "data-styles-preset": "Gb9Urlcot",
                                dir: "auto",
                                style: {
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                },
                                children:
                                  "Sorry, the page you are looking for does not exist or has been moved elsewhere.",
                              }),
                            }),
                            className: "framer-9tayef",
                            "data-framer-name": "Error Description",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(ResolveLinks, {
                    links: [
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                    ],
                    children: (resolvedLinks) =>
                      /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          aFsUc6yLS: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              180 +
                              0 +
                              0 +
                              622.2,
                          },
                          YAGFqqlki: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              150 +
                              0 +
                              0 +
                              421.2,
                          },
                        },
                        children: /*#__PURE__*/ _jsx(
                          ComponentViewportProvider,
                          {
                            height: 56,
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              0 +
                              241.8 +
                              0 +
                              622.2,
                            children: /*#__PURE__*/ _jsx(
                              ContainerWithOptimizedAppearEffect,
                              {
                                animate: animation4,
                                className: "framer-12oecnj-container",
                                "data-framer-appear-id": "12oecnj",
                                initial: animation5,
                                nodeId: "cqvRWA7_o",
                                optimized: true,
                                rendersWithMotion: true,
                                scopeId: "CzmevToMm",
                                children: /*#__PURE__*/ _jsx(
                                  PropertyOverrides,
                                  {
                                    breakpoint: baseVariant,
                                    overrides: {
                                      aFsUc6yLS: {
                                        xrwkWfCPt: resolvedLinks[1],
                                      },
                                      YAGFqqlki: {
                                        xrwkWfCPt: resolvedLinks[2],
                                      },
                                    },
                                    children: /*#__PURE__*/ _jsx(Button, {
                                      bI_rTu_15: "Back To Home",
                                      height: "100%",
                                      id: "cqvRWA7_o",
                                      layoutId: "cqvRWA7_o",
                                      variant: matchVariant("idTHluBYb"),
                                      width: "100%",
                                      xrwkWfCPt: resolvedLinks[0],
                                    }),
                                  }
                                ),
                              }
                            ),
                          }
                        ),
                      }),
                  }),
                ],
              }),
            ],
          }),
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  ".framer-bV7TU.framer-1j7s5ki, .framer-bV7TU .framer-1j7s5ki { display: block; }",
  ".framer-bV7TU.framer-1sims9x { align-content: center; align-items: center; background-color: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, #faf9ff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-bV7TU .framer-18vacpp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100vh; justify-content: flex-end; overflow: visible; padding: 0px 30px 80px 30px; position: relative; width: 100%; z-index: 1; }",
  ".framer-bV7TU .framer-li7ewk { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-filter-override, filter); }",
  ".framer-bV7TU .framer-1tz6r32 { background: linear-gradient(180deg, var(--token-b792d557-4853-49ac-865a-1d8073a4ab4e, rgba(174, 220, 253, 0.6)) 0%, rgb(250, 249, 255) 100%); bottom: 0px; flex: none; gap: 40px; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 100%; }",
  ".framer-bV7TU .framer-aa0hva { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; max-width: 723px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-bV7TU .framer-1of4jbr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-bV7TU .framer-crixkf { flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-bV7TU .framer-1qmqzj7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-bV7TU .framer-8dyj8m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-bV7TU .framer-rwtc7j, .framer-bV7TU .framer-1maulwa, .framer-bV7TU .framer-hwgd5e { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-bV7TU .framer-9tayef { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-bV7TU .framer-12oecnj-container { flex: none; height: auto; position: relative; width: auto; will-change: var(--framer-will-change-effect-override, transform); }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-bV7TU.framer-1sims9x { width: 810px; } .framer-bV7TU .framer-18vacpp { height: min-content; padding: 180px 30px 80px 30px; }}",
  "@media (max-width: 809.98px) { .framer-bV7TU.framer-1sims9x { width: 390px; } .framer-bV7TU .framer-18vacpp { gap: 40px; height: min-content; padding: 150px 20px 60px 20px; } .framer-bV7TU .framer-aa0hva { gap: 24px; } .framer-bV7TU .framer-1of4jbr { gap: 32px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1421
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"aFsUc6yLS":{"layout":["fixed","auto"]},"YAGFqqlki":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"iO9Sks8kp":{"pattern":":iO9Sks8kp","name":"nav"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerCzmevToMm = withCSS(Component, css, "framer-bV7TU");
export default FramerCzmevToMm;
FramerCzmevToMm.displayName = "Page";
FramerCzmevToMm.defaultProps = { height: 1421, width: 1200 };
addFonts(
  FramerCzmevToMm,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
          weight: "400",
        },
      ],
    },
    ...ButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerCzmevToMm.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(Button, {}, context)],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerCzmevToMm",
      slots: [],
      annotations: {
        framerResponsiveScreen: "true",
        framerIntrinsicHeight: "1421",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"aFsUc6yLS":{"layout":["fixed","auto"]},"YAGFqqlki":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerAcceptsLayoutTemplate: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1200",
        framerComponentViewportWidth: "true",
        framerScrollSections:
          '{"iO9Sks8kp":{"pattern":":iO9Sks8kp","name":"nav"}}',
      },
    },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
