// Generated by Framer (835d061)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "72rtr7", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "1f2m53s",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "1ghs8jd", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {
      DKjxuvnVL: "3",
      fNnkWXAhK: "5",
      iDeppvluH: "4",
      JOyHnHvAO: "2",
      KgChzwTDE: "tigger-1",
      W5f9_uuRU: "tigger4",
      wqdmfC7Gq: "nav",
      xham8q85I: "tigger2",
      xzMOALMBP: "1",
      YGkYp1bz1: "tigger3",
    },
    robots: "max-image-preview:large",
    serializationId: "framer-aGRht",
    title: siteMetadata(params, activeLocale).title || "Home",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
