// Generated by Framer (f0eed09)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "9efd4t", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "o434di",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "zqzy4m", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: { nL5ajOr3C: "nav" },
    robots: "max-image-preview:large",
    serializationId: "framer-A4oFk",
    title: siteMetadata(params, activeLocale).title || "Member",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
