// Generated by Framer (835d061)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Link,
  RichText,
  runTasksWithYield,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/dWWrdZxAvpA3fCXr4Ic4/cs9XIpNSU6trDI9GTpJF/bq5q0RP9E.js";
import * as sharedStyle from "https://framerusercontent.com/modules/3uvUzqtHOpRrr7gJTJhU/YkVGizH00aGbkCUQud7B/Gb9Urlcot.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/fk6IW0hN44iDIbsmKF3a/yd7iafobyNdXrl2a0V9M/ILq5RyVfl.js";
import * as sharedStyle4 from "https://framerusercontent.com/modules/J27WFeWJ2tuVdB7XE9gD/EBJ2QBYfKdi4RbnMYs01/nEa5QGSkK.js";
import * as sharedStyle5 from "https://framerusercontent.com/modules/Kl0eSBWkEZOx34i16sNn/JSgGnhsOlMiPHvq0qwTS/su9gcpKDq.js";
import * as sharedStyle3 from "https://framerusercontent.com/modules/TAbCb7DbtTwpZTp75ySa/XDsHE9EApsaKA5nUeCIu/yV61UC4Uw.js";
import Group from "https://framerusercontent.com/modules/F5lEwgopVUbv7rnMnlCM/HIFf00JiYaKIa4baJLmj/GbOIX0Y9D.js";
import Vector from "https://framerusercontent.com/modules/mDj1oCTloQhDB1dWO0u3/8bXn9RGNyrjyPY4KzFgC/NmgLhsag9.js";
import FacebookAppSymbol1 from "https://framerusercontent.com/modules/XDsjnW3BVg4eyVozLVTx/rYMmh8tRzNMdQqF7uf3s/Nszylv1jq.js";
import Twitter from "https://framerusercontent.com/modules/rttzt2ABBA3quPSRijfX/UewsQCjFmVduWr3RKnp2/WGyyYPtjA.js";
const TwitterFonts = getFonts(Twitter);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["FRhTH0Xal", "kBlER_GoH", "S8RmJvmun"];
const serializationHash = "framer-vLysk";
const variantClassNames = {
  FRhTH0Xal: "framer-v-12h7ah5",
  kBlER_GoH: "framer-v-1psu1in",
  S8RmJvmun: "framer-v-c8arms",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 24,
};
const transition2 = {
  delay: 0.2,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 24,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "FRhTH0Xal",
  Phone: "S8RmJvmun",
  Tablet: "kBlER_GoH",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "FRhTH0Xal",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "FRhTH0Xal",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
    sharedStyle4.className,
    sharedStyle5.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-12h7ah5",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "FRhTH0Xal",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              kBlER_GoH: { "data-framer-name": "Tablet" },
              S8RmJvmun: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(MotionDivWithFX, {
            __framer__animate: { transition: transition2 },
            __framer__animateOnce: true,
            __framer__enter: animation,
            __framer__exit: animation1,
            __framer__styleAppearEffectEnabled: true,
            __framer__threshold: 0,
            __perspectiveFX: false,
            __smartComponentFX: true,
            __targetOpacity: 1,
            className: "framer-1rp0ykm",
            "data-framer-name": "Container",
            layoutDependency: layoutDependency,
            layoutId: "n62UznPms",
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-kx3lcr",
                "data-framer-name": "Footer Links",
                layoutDependency: layoutDependency,
                layoutId: "YxHZS6A0J",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-t4bwta",
                    "data-framer-name": "Social Links",
                    layoutDependency: layoutDependency,
                    layoutId: "TdzU1WgNo",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-3t2hdp",
                        "data-framer-name": "Social Link Container",
                        layoutDependency: layoutDependency,
                        layoutId: "VRQvqIin0",
                        children: [
                          /*#__PURE__*/ _jsx(Link, {
                            href: { webPageId: "augiA20Il" },
                            motionChild: true,
                            nodeId: "zqBtVyevK",
                            openInNewTab: false,
                            scopeId: "TIdIYLxt7",
                            children: /*#__PURE__*/ _jsx(Image1, {
                              as: "a",
                              background: {
                                alt: "",
                                fit: "fill",
                                intrinsicHeight: 30,
                                intrinsicWidth: 103,
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    110 +
                                    (((componentViewport?.height || 621) -
                                      170 -
                                      488) /
                                      2 +
                                      0 +
                                      0) +
                                    0 +
                                    0 +
                                    0 +
                                    0 +
                                    0 +
                                    0 +
                                    0
                                ),
                                pixelHeight: 30,
                                pixelWidth: 103,
                                sizes: "171.6667px",
                                src: "https://framerusercontent.com/images/8N8ecWxjF2M53fFMe8qYYByOmRI.svg?width=103&height=30",
                              },
                              className: "framer-1rw7d5o framer-yu73ly",
                              fitImageDimension: "width",
                              layoutDependency: layoutDependency,
                              layoutId: "zqBtVyevK",
                              ...addPropertyOverrides(
                                {
                                  kBlER_GoH: {
                                    background: {
                                      alt: "",
                                      fit: "fill",
                                      intrinsicHeight: 30,
                                      intrinsicWidth: 103,
                                      loading: getLoadingLazyAtYPosition(
                                        (componentViewport?.y || 0) +
                                          80 +
                                          (((componentViewport?.height || 843) -
                                            120 -
                                            777) /
                                            2 +
                                            0 +
                                            0) +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0
                                      ),
                                      pixelHeight: 30,
                                      pixelWidth: 103,
                                      sizes: "123.6px",
                                      src: "https://framerusercontent.com/images/8N8ecWxjF2M53fFMe8qYYByOmRI.svg?width=103&height=30",
                                    },
                                  },
                                  S8RmJvmun: {
                                    background: {
                                      alt: "",
                                      fit: "fill",
                                      intrinsicHeight: 30,
                                      intrinsicWidth: 103,
                                      loading: getLoadingLazyAtYPosition(
                                        (componentViewport?.y || 0) +
                                          60 +
                                          (((componentViewport?.height ||
                                            1164) -
                                            90 -
                                            1209) /
                                            2 +
                                            0 +
                                            0) +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0 +
                                          0
                                      ),
                                      pixelHeight: 30,
                                      pixelWidth: 103,
                                      sizes: "109.8667px",
                                      src: "https://framerusercontent.com/images/8N8ecWxjF2M53fFMe8qYYByOmRI.svg?width=103&height=30",
                                    },
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-7k06ux",
                                "data-styles-preset": "Gb9Urlcot",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                },
                                children:
                                  "Providing trusted dental care, modern treatments, and healthy smiles for patients with comfort, confidence, and quality.",
                              }),
                            }),
                            className: "framer-q15gru",
                            "data-framer-name": "Social Link Description",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "qMvBrKFPX",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1eryfyh",
                        "data-framer-name": "Social Link Items",
                        layoutDependency: layoutDependency,
                        layoutId: "RGvmd65Bu",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-eq5x9f",
                                "data-styles-preset": "bq5q0RP9E",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                                },
                                children: "Follow us on :",
                              }),
                            }),
                            className: "framer-5jx296",
                            "data-framer-name": "Follow Us Label",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "z0vrPGkZA",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-xvhidb",
                            "data-framer-name": "Social Link",
                            layoutDependency: layoutDependency,
                            layoutId: "HC2uvXCir",
                            children: [
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 50,
                                width: "50px",
                                y:
                                  (componentViewport?.y || 0) +
                                  110 +
                                  (((componentViewport?.height || 621) -
                                    170 -
                                    488) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  0 +
                                  0 +
                                  0 +
                                  277 +
                                  0 +
                                  0,
                                ...addPropertyOverrides(
                                  {
                                    kBlER_GoH: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        80 +
                                        (((componentViewport?.height || 843) -
                                          120 -
                                          777) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        243 +
                                        0 +
                                        0,
                                    },
                                    S8RmJvmun: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        60 +
                                        (((componentViewport?.height || 1164) -
                                          90 -
                                          1209) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        223 +
                                        0 +
                                        0,
                                    },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-1v77cay-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "ScHtv7gWl-container",
                                    nodeId: "ScHtv7gWl",
                                    rendersWithMotion: true,
                                    scopeId: "TIdIYLxt7",
                                    children: /*#__PURE__*/ _jsx(Twitter, {
                                      A8UmaZ79X:
                                        "var(--token-9f10c85b-2edf-4ef9-96e0-f3e6553d041f, rgb(238, 242, 253))",
                                      fO5hhfrCO: "https://x.com/alevweb",
                                      height: "100%",
                                      id: "ScHtv7gWl",
                                      J1hUlGYO7: "8px",
                                      layoutId: "ScHtv7gWl",
                                      style: { height: "100%", width: "100%" },
                                      vBnxOk0FE: Vector,
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }),
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 50,
                                width: "50px",
                                y:
                                  (componentViewport?.y || 0) +
                                  110 +
                                  (((componentViewport?.height || 621) -
                                    170 -
                                    488) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  0 +
                                  0 +
                                  0 +
                                  277 +
                                  0 +
                                  0,
                                ...addPropertyOverrides(
                                  {
                                    kBlER_GoH: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        80 +
                                        (((componentViewport?.height || 843) -
                                          120 -
                                          777) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        243 +
                                        0 +
                                        0,
                                    },
                                    S8RmJvmun: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        60 +
                                        (((componentViewport?.height || 1164) -
                                          90 -
                                          1209) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        223 +
                                        0 +
                                        0,
                                    },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-1jk00sd-container",
                                    "data-framer-name": "in",
                                    layoutDependency: layoutDependency,
                                    layoutId: "salXpRiXO-container",
                                    name: "in",
                                    nodeId: "salXpRiXO",
                                    rendersWithMotion: true,
                                    scopeId: "TIdIYLxt7",
                                    children: /*#__PURE__*/ _jsx(Twitter, {
                                      A8UmaZ79X:
                                        "var(--token-9f10c85b-2edf-4ef9-96e0-f3e6553d041f, rgb(238, 242, 253))",
                                      fO5hhfrCO: "https://www.linkedin.com/",
                                      height: "100%",
                                      id: "salXpRiXO",
                                      J1hUlGYO7: "8px",
                                      layoutId: "salXpRiXO",
                                      name: "in",
                                      style: { height: "100%", width: "100%" },
                                      vBnxOk0FE: Group,
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }),
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 50,
                                width: "50px",
                                y:
                                  (componentViewport?.y || 0) +
                                  110 +
                                  (((componentViewport?.height || 621) -
                                    170 -
                                    488) /
                                    2 +
                                    0 +
                                    0) +
                                  0 +
                                  0 +
                                  0 +
                                  0 +
                                  277 +
                                  0 +
                                  0,
                                ...addPropertyOverrides(
                                  {
                                    kBlER_GoH: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        80 +
                                        (((componentViewport?.height || 843) -
                                          120 -
                                          777) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        243 +
                                        0 +
                                        0,
                                    },
                                    S8RmJvmun: {
                                      y:
                                        (componentViewport?.y || 0) +
                                        60 +
                                        (((componentViewport?.height || 1164) -
                                          90 -
                                          1209) /
                                          2 +
                                          0 +
                                          0) +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        0 +
                                        223 +
                                        0 +
                                        0,
                                    },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-991km-container",
                                    "data-framer-name": "facebook",
                                    layoutDependency: layoutDependency,
                                    layoutId: "qCns2QJU1-container",
                                    name: "facebook",
                                    nodeId: "qCns2QJU1",
                                    rendersWithMotion: true,
                                    scopeId: "TIdIYLxt7",
                                    children: /*#__PURE__*/ _jsx(Twitter, {
                                      A8UmaZ79X:
                                        "var(--token-9f10c85b-2edf-4ef9-96e0-f3e6553d041f, rgb(238, 242, 253))",
                                      fO5hhfrCO:
                                        "https://www.facebook.com/alevweb/",
                                      height: "100%",
                                      id: "qCns2QJU1",
                                      J1hUlGYO7: "8px",
                                      layoutId: "qCns2QJU1",
                                      name: "facebook",
                                      style: { height: "100%", width: "100%" },
                                      vBnxOk0FE: FacebookAppSymbol1,
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }),
                            ],
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-kqber3",
                    "data-framer-name": "Links Container",
                    layoutDependency: layoutDependency,
                    layoutId: "SHh8mRfNF",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-18vzgay",
                        "data-framer-name": "Useful Links",
                        layoutDependency: layoutDependency,
                        layoutId: "zKEH_ZTcV",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-yd8c4f",
                                "data-styles-preset": "ILq5RyVfl",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                                },
                                children: "Useful Links",
                              }),
                            }),
                            className: "framer-1xuqbou",
                            "data-framer-name": "Useful Links Title",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "Gi_zz4V46",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-1qvp1js",
                            "data-framer-name": "Links List",
                            layoutDependency: layoutDependency,
                            layoutId: "lhx8nA3CT",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "augiA20Il" },
                                      motionChild: true,
                                      nodeId: "JjL0gKT27",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Home ",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1fri62e",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "JjL0gKT27",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "O37Q3q2oz" },
                                      motionChild: true,
                                      nodeId: "f30MlV1dp",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "About Us",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-agnxe4",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "f30MlV1dp",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "QQGVgSF_N" },
                                      motionChild: true,
                                      nodeId: "y6cagjo6B",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Services",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1rs489c",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "y6cagjo6B",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "DJv88PODh" },
                                      motionChild: true,
                                      nodeId: "Wi4M1ktNA",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Members",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-iqru3q",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "Wi4M1ktNA",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "Clt_sSJfV" },
                                      motionChild: true,
                                      nodeId: "OXpXVKttb",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Contact Us",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1ngn662",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "OXpXVKttb",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1usm0lu",
                        "data-framer-name": "Inner Pages",
                        layoutDependency: layoutDependency,
                        layoutId: "ignqTWb4d",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-yd8c4f",
                                "data-styles-preset": "ILq5RyVfl",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                                },
                                children: "Inner Pages",
                              }),
                            }),
                            className: "framer-12ipto1",
                            "data-framer-name": "Inner Pages Title",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "CXbq2y0zV",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-176lg9q",
                            "data-framer-name": "Links List",
                            layoutDependency: layoutDependency,
                            layoutId: "zvmO0TkIm",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: {
                                        pathVariables: {
                                          UoIu0EK0h: "dr.-sophia-miller",
                                        },
                                        unresolvedPathSlugs: {
                                          UoIu0EK0h: {
                                            collectionId: "iX6CZ_7pr",
                                            collectionItemId: "T89cQiC8k",
                                          },
                                        },
                                        webPageId: "zTXU1o_sn",
                                      },
                                      motionChild: true,
                                      nodeId: "Uq7Bwba6b",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Member Details ",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1wxkghl",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "Uq7Bwba6b",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: {
                                        pathVariables: {
                                          Xp0UqGBJA: "oral-surgery",
                                        },
                                        unresolvedPathSlugs: {
                                          Xp0UqGBJA: {
                                            collectionId: "QSkWLVmAe",
                                            collectionItemId: "jxqKE9qjV",
                                          },
                                        },
                                        webPageId: "x5GdRXF3b",
                                      },
                                      motionChild: true,
                                      nodeId: "yPct71AlP",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Service Details ",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-zt3xj9",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "yPct71AlP",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "CkGraAsmb" },
                                      motionChild: true,
                                      nodeId: "bzE6V6JnN",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Blog & News",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1acyoe8",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "bzE6V6JnN",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: {
                                        pathVariables: {
                                          fluoa2Chd:
                                            "best-foods-for-healthy-teeth-growth",
                                        },
                                        unresolvedPathSlugs: {
                                          fluoa2Chd: {
                                            collectionId: "snWrVl_L5",
                                            collectionItemId: "yP69kalk9",
                                          },
                                        },
                                        webPageId: "Av0juBD09",
                                      },
                                      motionChild: true,
                                      nodeId: "LxAgT5FZw",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Blog Details",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-1oot30y",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "LxAgT5FZw",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1i8l677",
                        "data-framer-name": "Inner Pages",
                        layoutDependency: layoutDependency,
                        layoutId: "Idzc91UwP",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-yd8c4f",
                                "data-styles-preset": "ILq5RyVfl",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                                },
                                children: "Utility Pages",
                              }),
                            }),
                            className: "framer-1m8y7ga",
                            "data-framer-name": "Inner Pages Title",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "PK626q3E5",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              "--framer-paragraph-spacing": "0px",
                            },
                            verticalAlignment: "center",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-1bi47jl",
                            "data-framer-name": "Links List",
                            layoutDependency: layoutDependency,
                            layoutId: "GKc91DqDK",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: {
                                        pathVariables: {
                                          jxt7UQSHI: "privacy-policy",
                                        },
                                        unresolvedPathSlugs: {
                                          jxt7UQSHI: {
                                            collectionId: "BqdJRSU4x",
                                            collectionItemId: "gjGEFp7zk",
                                          },
                                        },
                                        webPageId: "CdkisGZLh",
                                      },
                                      motionChild: true,
                                      nodeId: "JcL03_gCL",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "Privacy Policy",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-x0d8hf",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "JcL03_gCL",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1iro191",
                                    "data-styles-preset": "yV61UC4Uw",
                                    dir: "auto",
                                    style: {
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                      href: { webPageId: "CzmevToMm" },
                                      motionChild: true,
                                      nodeId: "T1AWq4Zys",
                                      openInNewTab: false,
                                      relValues: [],
                                      scopeId: "TIdIYLxt7",
                                      smoothScroll: false,
                                      children: /*#__PURE__*/ _jsx(motion.a, {
                                        className:
                                          "framer-styles-preset-1teis7h",
                                        "data-styles-preset": "nEa5QGSkK",
                                        children: "404",
                                      }),
                                    }),
                                  }),
                                }),
                                className: "framer-so1nzi",
                                "data-framer-name": "Link",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "T1AWq4Zys",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                  "--framer-paragraph-spacing": "0px",
                                  opacity: 0.8,
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-17oflfd",
                "data-border": true,
                "data-framer-name": "Company Info",
                layoutDependency: layoutDependency,
                layoutId: "oPgisvu8R",
                style: {
                  "--border-bottom-width": "0px",
                  "--border-color":
                    "var(--token-5e421d18-5d17-4869-827f-e8cec0385dad, rgba(10, 15, 50, 0.2))",
                  "--border-left-width": "0px",
                  "--border-right-width": "0px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                },
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-eq5x9f",
                        "data-styles-preset": "bq5q0RP9E",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                        },
                        children:
                          "\xa9 2026 GlowDent. All Rights Reserved. Trusted dental care and healthy smiles.",
                      }),
                    }),
                    className: "framer-fcx1oj",
                    "data-framer-name": "Copyright",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "gIiW9_MP_",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs(motion.p, {
                        className: "framer-styles-preset-eq5x9f",
                        "data-styles-preset": "bq5q0RP9E",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                        },
                        children: [
                          "Website By ",
                          /*#__PURE__*/ _jsx(Link, {
                            href: "https://www.framer.com/@alev-web/",
                            motionChild: true,
                            nodeId: "DkGHPkABW",
                            openInNewTab: true,
                            relValues: [],
                            scopeId: "TIdIYLxt7",
                            smoothScroll: false,
                            children: /*#__PURE__*/ _jsx(motion.a, {
                              className: "framer-styles-preset-1ucxh68",
                              "data-styles-preset": "su9gcpKDq",
                              children: /*#__PURE__*/ _jsx(motion.span, {
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-hl0iuy, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                                },
                                children: "Aleweb",
                              }),
                            }),
                          }),
                        ],
                      }),
                    }),
                    className: "framer-9gvliv",
                    "data-framer-name": "Copyright",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "DkGHPkABW",
                    style: {
                      "--extracted-hl0iuy":
                        "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                      "--extracted-r6o4lv":
                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-vLysk.framer-yu73ly, .framer-vLysk .framer-yu73ly { display: block; }",
  ".framer-vLysk.framer-12h7ah5 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 110px 30px 60px 30px; position: relative; width: 1200px; }",
  ".framer-vLysk .framer-1rp0ykm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 110px; height: min-content; justify-content: center; max-width: 1296px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-vLysk .framer-kx3lcr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-vLysk .framer-t4bwta { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; max-width: 416px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-vLysk .framer-3t2hdp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-vLysk .framer-1rw7d5o { flex: none; height: 50px; overflow: visible; position: relative; text-decoration: none; width: auto; }",
  ".framer-vLysk .framer-q15gru { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-vLysk .framer-1eryfyh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-vLysk .framer-5jx296, .framer-vLysk .framer-1xuqbou, .framer-vLysk .framer-1fri62e, .framer-vLysk .framer-agnxe4, .framer-vLysk .framer-1rs489c, .framer-vLysk .framer-iqru3q, .framer-vLysk .framer-1ngn662, .framer-vLysk .framer-12ipto1, .framer-vLysk .framer-1wxkghl, .framer-vLysk .framer-zt3xj9, .framer-vLysk .framer-1acyoe8, .framer-vLysk .framer-1oot30y, .framer-vLysk .framer-1m8y7ga, .framer-vLysk .framer-x0d8hf, .framer-vLysk .framer-so1nzi, .framer-vLysk .framer-fcx1oj, .framer-vLysk .framer-9gvliv { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-vLysk .framer-xvhidb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
  ".framer-vLysk .framer-1v77cay-container, .framer-vLysk .framer-1jk00sd-container, .framer-vLysk .framer-991km-container { flex: none; height: 50px; position: relative; width: 50px; }",
  ".framer-vLysk .framer-kqber3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 676px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-vLysk .framer-18vzgay, .framer-vLysk .framer-1usm0lu, .framer-vLysk .framer-1i8l677 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-vLysk .framer-1qvp1js { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: auto; }",
  ".framer-vLysk .framer-176lg9q, .framer-vLysk .framer-1bi47jl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-vLysk .framer-17oflfd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 24px 0px 0px 0px; position: relative; width: 100%; }",
  ".framer-vLysk.framer-v-1psu1in.framer-12h7ah5 { padding: 80px 30px 40px 30px; width: 810px; }",
  ".framer-vLysk.framer-v-1psu1in .framer-1rp0ykm { gap: 60px; }",
  ".framer-vLysk.framer-v-1psu1in .framer-kx3lcr { flex-direction: column; gap: 60px; justify-content: center; }",
  ".framer-vLysk.framer-v-1psu1in .framer-t4bwta { flex: none; gap: 40px; width: 100%; }",
  ".framer-vLysk.framer-v-1psu1in .framer-1rw7d5o { height: 36px; }",
  ".framer-vLysk.framer-v-1psu1in .framer-kqber3 { flex: none; max-width: unset; width: 100%; }",
  ".framer-vLysk.framer-v-1psu1in .framer-18vzgay, .framer-vLysk.framer-v-1psu1in .framer-1usm0lu, .framer-vLysk.framer-v-1psu1in .framer-1i8l677 { gap: 32px; }",
  ".framer-vLysk.framer-v-1psu1in .framer-17oflfd, .framer-vLysk.framer-v-c8arms .framer-17oflfd { flex-direction: column; gap: 4px; justify-content: center; }",
  ".framer-vLysk.framer-v-c8arms.framer-12h7ah5 { padding: 60px 20px 30px 20px; width: 390px; }",
  ".framer-vLysk.framer-v-c8arms .framer-1rp0ykm { gap: 40px; }",
  ".framer-vLysk.framer-v-c8arms .framer-kx3lcr { flex-direction: column; gap: 40px; justify-content: center; }",
  ".framer-vLysk.framer-v-c8arms .framer-t4bwta { flex: none; gap: 32px; width: 100%; }",
  ".framer-vLysk.framer-v-c8arms .framer-3t2hdp, .framer-vLysk.framer-v-c8arms .framer-1usm0lu, .framer-vLysk.framer-v-c8arms .framer-1i8l677 { gap: 24px; }",
  ".framer-vLysk.framer-v-c8arms .framer-1rw7d5o { height: 32px; }",
  ".framer-vLysk.framer-v-c8arms .framer-xvhidb { gap: 14px; }",
  ".framer-vLysk.framer-v-c8arms .framer-kqber3 { flex: none; flex-direction: column; gap: 24px 60px; justify-content: center; max-width: unset; width: 100%; }",
  ".framer-vLysk.framer-v-c8arms .framer-18vzgay { gap: 4px; }",
  ".framer-vLysk.framer-v-c8arms .framer-fcx1oj { white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  ...sharedStyle4.css,
  ...sharedStyle5.css,
  '.framer-vLysk[data-border="true"]::after, .framer-vLysk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 621
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"kBlER_GoH":{"layout":["fixed","auto"]},"S8RmJvmun":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTIdIYLxt7 = withCSS(Component, css, "framer-vLysk");
export default FramerTIdIYLxt7;
FramerTIdIYLxt7.displayName = "Footer";
FramerTIdIYLxt7.defaultProps = { height: 621, width: 1200 };
addPropertyControls(FramerTIdIYLxt7, {
  variant: {
    options: ["FRhTH0Xal", "kBlER_GoH", "S8RmJvmun"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerTIdIYLxt7,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...TwitterFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
    ...getFontsFromSharedStyle(sharedStyle4.fonts),
    ...getFontsFromSharedStyle(sharedStyle5.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerTIdIYLxt7.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(Twitter, {}, context)],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerTIdIYLxt7",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerIntrinsicHeight: "621",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1200",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"kBlER_GoH":{"layout":["fixed","auto"]},"S8RmJvmun":{"layout":["fixed","auto"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
