// Generated by Framer (7f863c8)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import WhyChhoseCard from "https://framerusercontent.com/modules/8cCFUfJgW3A4gUuchYOU/dh5z2VnIc2plFZ6Icmb9/c9SFuRFRY.js";
const WhyChhoseCardFonts = getFonts(WhyChhoseCard);
const cycleOrder = ["JUWkgvUEi", "ZklkZe4_7", "pDFEMdRXo", "Dw9gN9Nsi"];
const serializationHash = "framer-22C2P";
const variantClassNames = {
  Dw9gN9Nsi: "framer-v-etdpwo",
  JUWkgvUEi: "framer-v-1ndsy81",
  pDFEMdRXo: "framer-v-1qg8qj6",
  ZklkZe4_7: "framer-v-cn3r6o",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Desktop 1": "JUWkgvUEi",
  "Desktop 2": "ZklkZe4_7",
  "Desktop 3": "pDFEMdRXo",
  "Desktop 4": "Dw9gN9Nsi",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "JUWkgvUEi",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "JUWkgvUEi",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const HNCLVaJ8C12nrayr = activeVariantCallback(async (...args) => {
    setVariant("JUWkgvUEi");
  });
  const HNCLVaJ8Cr66b0 = activeVariantCallback(async (...args) => {
    setVariant("ZklkZe4_7");
  });
  const HNCLVaJ8Cgjwbri = activeVariantCallback(async (...args) => {
    setVariant("pDFEMdRXo");
  });
  const HNCLVaJ8C2vshmr = activeVariantCallback(async (...args) => {
    setVariant("Dw9gN9Nsi");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1ndsy81",
            className,
            classNames
          ),
          "data-framer-name": "Desktop 1",
          layoutDependency: layoutDependency,
          layoutId: "JUWkgvUEi",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              Dw9gN9Nsi: { "data-framer-name": "Desktop 4" },
              pDFEMdRXo: { "data-framer-name": "Desktop 3" },
              ZklkZe4_7: { "data-framer-name": "Desktop 2" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 98,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 638) - 0 - 464) / 2 + 0 + 0),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-7q3hs8-container",
                layoutDependency: layoutDependency,
                layoutId: "XSBxM99pM-container",
                nodeId: "XSBxM99pM",
                rendersWithMotion: true,
                scopeId: "VDY_KHwkp",
                children: /*#__PURE__*/ _jsx(WhyChhoseCard, {
                  avzA_LL3n:
                    "We provide trusted dental care with experienced dentists, modern equipment, and a strong focus on patient comfort and satisfaction.",
                  Blb1YdNk1: "Experienced Dental Care Team",
                  height: "100%",
                  HNCLVaJ8C: HNCLVaJ8C12nrayr,
                  id: "XSBxM99pM",
                  layoutId: "XSBxM99pM",
                  style: { width: "100%" },
                  variant: matchVariant("atsFFsIQv"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      Dw9gN9Nsi: { variant: matchVariant("SJnui0OXR") },
                      pDFEMdRXo: { variant: matchVariant("SJnui0OXR") },
                      ZklkZe4_7: { variant: matchVariant("SJnui0OXR") },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 98,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 638) - 0 - 464) / 2 + 98 + 24),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1r29xbt-container",
                layoutDependency: layoutDependency,
                layoutId: "ezRJkuATf-container",
                nodeId: "ezRJkuATf",
                rendersWithMotion: true,
                scopeId: "VDY_KHwkp",
                children: /*#__PURE__*/ _jsx(WhyChhoseCard, {
                  avzA_LL3n:
                    "We provide trusted dental care with experienced dentists, modern equipment, and a strong focus on patient comfort and satisfaction.",
                  Blb1YdNk1: "Advanced Modern Technology Use",
                  height: "100%",
                  HNCLVaJ8C: HNCLVaJ8Cr66b0,
                  id: "ezRJkuATf",
                  layoutId: "ezRJkuATf",
                  style: { width: "100%" },
                  variant: matchVariant("SJnui0OXR"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { ZklkZe4_7: { variant: matchVariant("atsFFsIQv") } },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 98,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 638) - 0 - 464) / 2 + 196 + 48),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-13z9q75-container",
                layoutDependency: layoutDependency,
                layoutId: "CpMT9nxW3-container",
                nodeId: "CpMT9nxW3",
                rendersWithMotion: true,
                scopeId: "VDY_KHwkp",
                children: /*#__PURE__*/ _jsx(WhyChhoseCard, {
                  avzA_LL3n:
                    "We provide trusted dental care with experienced dentists, modern equipment, and a strong focus on patient comfort and satisfaction.",
                  Blb1YdNk1: "Gentle Patient Friendly Care",
                  height: "100%",
                  HNCLVaJ8C: HNCLVaJ8Cgjwbri,
                  id: "CpMT9nxW3",
                  layoutId: "CpMT9nxW3",
                  style: { width: "100%" },
                  variant: matchVariant("SJnui0OXR"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { pDFEMdRXo: { variant: matchVariant("atsFFsIQv") } },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 98,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 638) - 0 - 464) / 2 + 294 + 72),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1hrew5b-container",
                layoutDependency: layoutDependency,
                layoutId: "rDK3Dj9Fp-container",
                nodeId: "rDK3Dj9Fp",
                rendersWithMotion: true,
                scopeId: "VDY_KHwkp",
                children: /*#__PURE__*/ _jsx(WhyChhoseCard, {
                  avzA_LL3n:
                    "We provide trusted dental care with experienced dentists, modern equipment, and a strong focus on patient comfort and satisfaction.",
                  Blb1YdNk1: "Affordable Quality Dental Services",
                  height: "100%",
                  HNCLVaJ8C: HNCLVaJ8C2vshmr,
                  id: "rDK3Dj9Fp",
                  layoutId: "rDK3Dj9Fp",
                  style: { width: "100%" },
                  variant: matchVariant("SJnui0OXR"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { Dw9gN9Nsi: { variant: matchVariant("atsFFsIQv") } },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-22C2P.framer-1q3e3ku, .framer-22C2P .framer-1q3e3ku { display: block; }",
  ".framer-22C2P.framer-1ndsy81 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 558px; }",
  ".framer-22C2P .framer-7q3hs8-container, .framer-22C2P .framer-1r29xbt-container, .framer-22C2P .framer-13z9q75-container, .framer-22C2P .framer-1hrew5b-container { flex: none; height: auto; position: relative; width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 638
 * @framerIntrinsicWidth 558
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ZklkZe4_7":{"layout":["fixed","auto"]},"pDFEMdRXo":{"layout":["fixed","auto"]},"Dw9gN9Nsi":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerVDY_KHwkp = withCSS(Component, css, "framer-22C2P");
export default FramerVDY_KHwkp;
FramerVDY_KHwkp.displayName = "Why Choose tab";
FramerVDY_KHwkp.defaultProps = { height: 638, width: 558 };
addPropertyControls(FramerVDY_KHwkp, {
  variant: {
    options: ["JUWkgvUEi", "ZklkZe4_7", "pDFEMdRXo", "Dw9gN9Nsi"],
    optionTitles: ["Desktop 1", "Desktop 2", "Desktop 3", "Desktop 4"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerVDY_KHwkp,
  [{ explicitInter: true, fonts: [] }, ...WhyChhoseCardFonts],
  { supportsExplicitInterCodegen: true }
);
FramerVDY_KHwkp.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(WhyChhoseCard, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerVDY_KHwkp",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "558",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "638",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ZklkZe4_7":{"layout":["fixed","auto"]},"pDFEMdRXo":{"layout":["fixed","auto"]},"Dw9gN9Nsi":{"layout":["fixed","auto"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
