// Generated by Framer (0e6a859)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  getWhereExpressionFromPathVariables,
  Image as Image1,
  NotFoundError,
  PropertyOverrides,
  queryCache,
  RichText,
  runTasksWithYield,
  useComponentViewport,
  useCurrentPathVariables,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleCode,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  useRouteElementId,
  useSiteRefs,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import SocialShareButtons from "https://framerusercontent.com/modules/Y8fmn5ag0mIuZeI9kEFw/UAMeBv2HcGr9pJj3xyqJ/ShareButton.js";
import SectionTag from "#framer/local/canvasComponent/F2GdECUJ5/F2GdECUJ5.js";
import FAQSection from "#framer/local/canvasComponent/S8ygGzZl3/S8ygGzZl3.js";
import Blog from "#framer/local/collection/snWrVl_L5/snWrVl_L5.js";
import * as sharedStyle7 from "#framer/local/css/anOlvMCER/anOlvMCER.js";
import * as sharedStyle5 from "#framer/local/css/BczsPivWE/BczsPivWE.js";
import * as sharedStyle1 from "#framer/local/css/Gb9Urlcot/Gb9Urlcot.js";
import * as sharedStyle2 from "#framer/local/css/itDzyk8Gn/itDzyk8Gn.js";
import * as sharedStyle4 from "#framer/local/css/K6baPjkRU/K6baPjkRU.js";
import * as sharedStyle3 from "#framer/local/css/M2ZVMCuTT/M2ZVMCuTT.js";
import * as sharedStyle from "#framer/local/css/MVvA5iU4p/MVvA5iU4p.js";
import * as sharedStyle6 from "#framer/local/css/xaK4FL4sA/xaK4FL4sA.js";
import * as sharedStyle8 from "#framer/local/css/yV61UC4Uw/yV61UC4Uw.js";
import metadataProvider from "#framer/local/webPageMetadata/Av0juBD09/Av0juBD09.js";
const SectionTagFonts = getFonts(SectionTag);
const MotionDivWithOptimizedAppearEffect = withOptimizedAppearEffect(
  motion.div
);
const Image1WithOptimizedAppearEffect = withOptimizedAppearEffect(Image1);
const RichTextWithFX = withFX(RichText);
const SocialShareButtonsFonts = getFonts(SocialShareButtons);
const MotionDivWithFX = withFX(motion.div);
const FAQSectionFonts = getFonts(FAQSection);
const breakpoints = {
  hN6dYprvu: "(min-width: 1200px)",
  ntG6bbQkW: "(max-width: 809.98px)",
  y3zZhMkVk: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-SzEVH";
const variantClassNames = {
  hN6dYprvu: "framer-v-12i5nu7",
  ntG6bbQkW: "framer-v-m9o412",
  y3zZhMkVk: "framer-v-vn8hlx",
};
const HNZwP4TSk = undefined;
const jbrxNfn5F = undefined;
const qP7P1gcm4 = undefined;
const LkNWWjzki = undefined;
const saSYcLZpj = undefined;
const Jsd4z62fH = undefined;
const bP3PRzGIQ = undefined;
const vS8ZBnEAU = undefined;
const YLMlynKkk = undefined;
const updatedAt = undefined;
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const transition1 = {
  delay: 0,
  duration: 1,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: -150,
  y: 0,
};
const transition2 = {
  delay: 0,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation3 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 24,
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const animation4 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 150,
  y: 0,
};
const transition3 = {
  delay: 0.2,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation5 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition3,
  x: 0,
  y: 0,
};
const animation6 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const animation7 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition3,
  x: 0,
  y: 0,
};
const toString = (value) => {
  return typeof value === "string" ? value : String(value);
};
const suffix = (value, suffix) => {
  if (typeof value === "string" && typeof suffix === "string") {
    return value + suffix;
  } else if (typeof value === "string") {
    return value;
  } else if (typeof suffix === "string") {
    return suffix;
  }
  return "";
};
const sharedDateFormatter = (value, formatOptions, locale) => {
  if (typeof value !== "string") return "";
  const date = new Date(value);
  if (isNaN(date.getTime())) return "";
  const fallbackLocale = "en-US";
  try {
    return date.toLocaleString(locale || fallbackLocale, formatOptions);
  } catch {
    return date.toLocaleString(fallbackLocale, formatOptions);
  }
};
const dateOptions = { dateStyle: "long", timeZone: "UTC" };
const toDateString = (value, activeLocale) => {
  return sharedDateFormatter(value, dateOptions, activeLocale);
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "hN6dYprvu",
  Phone: "ntG6bbQkW",
  Tablet: "y3zZhMkVk",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const detailQuery = (where) => ({
  from: { alias: "Av0juBD09", data: Blog, type: "Collection" },
  select: [
    { collection: "Av0juBD09", name: "HNZwP4TSk", type: "Identifier" },
    { collection: "Av0juBD09", name: "Jsd4z62fH", type: "Identifier" },
    { collection: "Av0juBD09", name: "jbrxNfn5F", type: "Identifier" },
    { collection: "Av0juBD09", name: "LkNWWjzki", type: "Identifier" },
    { collection: "Av0juBD09", name: "saSYcLZpj", type: "Identifier" },
    { collection: "Av0juBD09", name: "qP7P1gcm4", type: "Identifier" },
    { collection: "Av0juBD09", name: "vS8ZBnEAU", type: "Identifier" },
    { collection: "Av0juBD09", name: "YLMlynKkk", type: "Identifier" },
    { collection: "Av0juBD09", name: "bP3PRzGIQ", type: "Identifier" },
    { collection: "Av0juBD09", name: "updatedAt", type: "Identifier" },
  ],
  where,
});
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "hN6dYprvu",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const currentPathVariables = useCurrentPathVariables();
  const [currentRouteData] = useQueryData(
    detailQuery(
      getWhereExpressionFromPathVariables(currentPathVariables, "Av0juBD09")
    )
  );
  const getFromCurrentRouteData = (key) => {
    if (!currentRouteData)
      throw new NotFoundError(
        `No data matches path variables: ${JSON.stringify(
          currentPathVariables
        )}`
      );
    return currentRouteData[key];
  };
  const {
    style,
    className,
    layoutId,
    variant,
    HNZwP4TSk = getFromCurrentRouteData("HNZwP4TSk") ?? "",
    Jsd4z62fH = getFromCurrentRouteData("Jsd4z62fH"),
    jbrxNfn5F = getFromCurrentRouteData("jbrxNfn5F") ?? "",
    LkNWWjzki = getFromCurrentRouteData("LkNWWjzki") ?? "",
    saSYcLZpj = getFromCurrentRouteData("saSYcLZpj") ?? "",
    qP7P1gcm4 = getFromCurrentRouteData("qP7P1gcm4"),
    vS8ZBnEAU = getFromCurrentRouteData("vS8ZBnEAU") ?? 0,
    YLMlynKkk = getFromCurrentRouteData("YLMlynKkk") ?? "",
    bP3PRzGIQ = getFromCurrentRouteData("bP3PRzGIQ") ?? "",
    updatedAt = getFromCurrentRouteData("updatedAt"),
    ...restProps
  } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({ HNZwP4TSk, Jsd4z62fH }, activeLocale),
    [Jsd4z62fH, HNZwP4TSk, activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
    sharedStyle4.className,
    sharedStyle5.className,
    sharedStyle6.className,
    sharedStyle7.className,
    sharedStyle8.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const elementId = useRouteElementId("BVdDj_lhC");
  const dynamicRef = useSiteRefs();
  const textContent = suffix(toString(vS8ZBnEAU), " min read");
  const activeLocaleCode = useLocaleCode();
  const textContent1 = toDateString(updatedAt, activeLocaleCode);
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "hN6dYprvu",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-12i5nu7", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-e86ide",
              "data-framer-name": "Hero Section",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsx("div", { className: "framer-kaidz1" }),
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-hwlwi9",
                  "data-framer-name": "Container",
                  id: elementId,
                  ref: dynamicRef(elementId),
                  children: [
                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        ntG6bbQkW: { animate: animation2, initial: animation3 },
                        y3zZhMkVk: { animate: animation2, initial: animation3 },
                      },
                      children: /*#__PURE__*/ _jsxs(
                        MotionDivWithOptimizedAppearEffect,
                        {
                          animate: animation,
                          className: "framer-1eoq2q3",
                          "data-framer-appear-id": "1eoq2q3",
                          "data-framer-name": "Text and Image Container",
                          initial: animation1,
                          optimized: true,
                          children: [
                            /*#__PURE__*/ _jsxs("div", {
                              className: "framer-19269h9",
                              "data-framer-name": "Text Container",
                              children: [
                                /*#__PURE__*/ _jsxs("div", {
                                  className: "framer-1gwpquc",
                                  "data-framer-name": "Header Content",
                                  children: [
                                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                                      breakpoint: baseVariant,
                                      overrides: {
                                        ntG6bbQkW: {
                                          y:
                                            (componentViewport?.y || 0) +
                                            0 +
                                            0 +
                                            150 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0,
                                        },
                                        y3zZhMkVk: {
                                          y:
                                            (componentViewport?.y || 0) +
                                            0 +
                                            0 +
                                            180 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0,
                                        },
                                      },
                                      children: /*#__PURE__*/ _jsx(
                                        ComponentViewportProvider,
                                        {
                                          height: 47,
                                          y:
                                            (componentViewport?.y || 0) +
                                            0 +
                                            0 +
                                            210 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            0,
                                          children: /*#__PURE__*/ _jsx(
                                            Container,
                                            {
                                              className:
                                                "framer-5isyyq-container",
                                              nodeId: "a6mG4_7m9",
                                              scopeId: "Av0juBD09",
                                              children: /*#__PURE__*/ _jsx(
                                                SectionTag,
                                                {
                                                  height: "100%",
                                                  id: "a6mG4_7m9",
                                                  j9h2sFaQp: "Blog Details",
                                                  layoutId: "a6mG4_7m9",
                                                  qbRh5Zv2v:
                                                    "var(--token-73b66216-b475-415b-b4b6-227679c18659, rgb(195, 230, 255))",
                                                  width: "100%",
                                                }
                                              ),
                                            }
                                          ),
                                        }
                                      ),
                                    }),
                                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                                      breakpoint: baseVariant,
                                      overrides: {
                                        ntG6bbQkW: {
                                          children: /*#__PURE__*/ _jsx(
                                            React.Fragment,
                                            {
                                              children: /*#__PURE__*/ _jsx(
                                                "h1",
                                                {
                                                  className:
                                                    "framer-styles-preset-b4fewl",
                                                  "data-styles-preset":
                                                    "MVvA5iU4p",
                                                  dir: "auto",
                                                  style: {
                                                    "--framer-text-alignment":
                                                      "center",
                                                    "--framer-text-color":
                                                      "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                                  },
                                                  children:
                                                    "Best Foods for Healthy Teeth Growth",
                                                }
                                              ),
                                            }
                                          ),
                                        },
                                      },
                                      children: /*#__PURE__*/ _jsx(RichText, {
                                        __fromCanvasComponent: true,
                                        children: /*#__PURE__*/ _jsx(
                                          React.Fragment,
                                          {
                                            children: /*#__PURE__*/ _jsx("h1", {
                                              className:
                                                "framer-styles-preset-b4fewl",
                                              "data-styles-preset": "MVvA5iU4p",
                                              dir: "auto",
                                              style: {
                                                "--framer-text-color":
                                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                              },
                                              children:
                                                "Best Foods for Healthy Teeth Growth",
                                            }),
                                          }
                                        ),
                                        className: "framer-5n8dse",
                                        "data-framer-name": "Header Title",
                                        fonts: ["Inter"],
                                        text: HNZwP4TSk,
                                        verticalAlignment: "top",
                                        withExternalLayout: true,
                                      }),
                                    }),
                                  ],
                                }),
                                /*#__PURE__*/ _jsx(PropertyOverrides, {
                                  breakpoint: baseVariant,
                                  overrides: {
                                    ntG6bbQkW: {
                                      children: /*#__PURE__*/ _jsx(
                                        React.Fragment,
                                        {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            className:
                                              "framer-styles-preset-7k06ux",
                                            "data-styles-preset": "Gb9Urlcot",
                                            dir: "auto",
                                            style: {
                                              "--framer-text-alignment":
                                                "center",
                                              "--framer-text-color":
                                                "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                            },
                                            children:
                                              "Brushing and flossing daily help keep teeth clean and gums healthy.",
                                          }),
                                        }
                                      ),
                                    },
                                  },
                                  children: /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx("p", {
                                          className:
                                            "framer-styles-preset-7k06ux",
                                          "data-styles-preset": "Gb9Urlcot",
                                          dir: "auto",
                                          style: {
                                            "--framer-text-color":
                                              "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                          },
                                          children:
                                            "Simple daily habits like brushing, flossing, and healthy eating help keep teeth strong, clean, and free from problems.",
                                        }),
                                      }
                                    ),
                                    className: "framer-1f5cf2w",
                                    "data-framer-name": "Body",
                                    fonts: ["Inter"],
                                    text: jbrxNfn5F,
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                  }),
                                }),
                              ],
                            }),
                            /*#__PURE__*/ _jsxs("div", {
                              className: "framer-1fddqhe",
                              "data-framer-name": "Avatar Group Label",
                              children: [
                                /*#__PURE__*/ _jsx(PropertyOverrides, {
                                  breakpoint: baseVariant,
                                  overrides: {
                                    ntG6bbQkW: {
                                      background: {
                                        alt: "",
                                        fit: "fill",
                                        loading: getLoadingLazyAtYPosition(
                                          (componentViewport?.y || 0) +
                                            0 +
                                            0 +
                                            150 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            337.2 +
                                            0 +
                                            0
                                        ),
                                        pixelHeight: 256,
                                        pixelWidth: 256,
                                        sizes: "64px",
                                        ...toResponsiveImage(qP7P1gcm4),
                                      },
                                    },
                                    y3zZhMkVk: {
                                      background: {
                                        alt: "",
                                        fit: "fill",
                                        loading: getLoadingLazyAtYPosition(
                                          (componentViewport?.y || 0) +
                                            0 +
                                            0 +
                                            180 +
                                            0 +
                                            0 +
                                            0 +
                                            0 +
                                            337.2 +
                                            0
                                        ),
                                        pixelHeight: 256,
                                        pixelWidth: 256,
                                        sizes: "64px",
                                        ...toResponsiveImage(qP7P1gcm4),
                                      },
                                    },
                                  },
                                  children: /*#__PURE__*/ _jsx(Image1, {
                                    background: {
                                      alt: "",
                                      fit: "fill",
                                      loading: getLoadingLazyAtYPosition(
                                        (componentViewport?.y || 0) +
                                          0 +
                                          0 +
                                          210 +
                                          0 +
                                          0 +
                                          0 +
                                          586 +
                                          0
                                      ),
                                      pixelHeight: 256,
                                      pixelWidth: 256,
                                      sizes: "64px",
                                      ...toResponsiveImage(qP7P1gcm4),
                                    },
                                    className: "framer-vko9jk",
                                    "data-framer-name": "Avatar",
                                  }),
                                }),
                                /*#__PURE__*/ _jsxs("div", {
                                  className: "framer-73829r",
                                  "data-framer-name": "Content",
                                  children: [
                                    /*#__PURE__*/ _jsx(RichText, {
                                      __fromCanvasComponent: true,
                                      children: /*#__PURE__*/ _jsx(
                                        React.Fragment,
                                        {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            className:
                                              "framer-styles-preset-it79c8",
                                            "data-styles-preset": "itDzyk8Gn",
                                            dir: "auto",
                                            style: {
                                              "--framer-text-color":
                                                "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                            },
                                            children: "Dr. Emily Carter",
                                          }),
                                        }
                                      ),
                                      className: "framer-t1v33l",
                                      "data-framer-name": "Author Name",
                                      fonts: ["Inter"],
                                      text: LkNWWjzki,
                                      verticalAlignment: "top",
                                      withExternalLayout: true,
                                    }),
                                    /*#__PURE__*/ _jsx(RichText, {
                                      __fromCanvasComponent: true,
                                      children: /*#__PURE__*/ _jsx(
                                        React.Fragment,
                                        {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            className:
                                              "framer-styles-preset-kbh8jg",
                                            "data-styles-preset": "M2ZVMCuTT",
                                            dir: "auto",
                                            style: {
                                              "--framer-text-color":
                                                "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                            },
                                            children: "Chief Dental Surgeon",
                                          }),
                                        }
                                      ),
                                      className: "framer-p813ky",
                                      "data-framer-name": "Author Title",
                                      fonts: ["Inter"],
                                      text: saSYcLZpj,
                                      verticalAlignment: "top",
                                      withExternalLayout: true,
                                    }),
                                  ],
                                }),
                              ],
                            }),
                          ],
                        }
                      ),
                    }),
                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        ntG6bbQkW: {
                          animate: animation5,
                          background: {
                            alt: "",
                            fit: "fill",
                            intrinsicHeight: 1300,
                            intrinsicWidth: 1100,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                0 +
                                0 +
                                150 +
                                0 +
                                0 +
                                502.2
                            ),
                            pixelHeight: 1552,
                            pixelWidth: 1128,
                            sizes: `min(${
                              componentViewport?.width || "100vw"
                            } - 40px, 1296px)`,
                            ...toResponsiveImage(Jsd4z62fH),
                          },
                          initial: animation3,
                        },
                        y3zZhMkVk: {
                          animate: animation5,
                          background: {
                            alt: "",
                            fit: "fill",
                            intrinsicHeight: 1300,
                            intrinsicWidth: 1100,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                0 +
                                0 +
                                180 +
                                0 +
                                0 +
                                461.2
                            ),
                            pixelHeight: 1552,
                            pixelWidth: 1128,
                            sizes: `min(${
                              componentViewport?.width || "100vw"
                            } - 60px, 1296px)`,
                            ...toResponsiveImage(Jsd4z62fH),
                          },
                          initial: animation3,
                        },
                      },
                      children: /*#__PURE__*/ _jsx(
                        Image1WithOptimizedAppearEffect,
                        {
                          animate: animation,
                          background: {
                            alt: "",
                            fit: "fill",
                            intrinsicHeight: 1300,
                            intrinsicWidth: 1100,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) + 0 + 0 + 210 + 0 + 0
                            ),
                            pixelHeight: 1552,
                            pixelWidth: 1128,
                            sizes: `min(max((min(${
                              componentViewport?.width || "100vw"
                            } - 60px, 1296px) - 72px) / 2, 1px), 550px)`,
                            ...toResponsiveImage(Jsd4z62fH),
                          },
                          className: "framer-10tve7r",
                          "data-framer-appear-id": "10tve7r",
                          initial: animation4,
                          optimized: true,
                        }
                      ),
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-1o1gpon",
              "data-framer-name": "Details",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsxs("div", {
                className: "framer-1xewqon",
                "data-framer-name": "Container",
                children: [
                  /*#__PURE__*/ _jsx(RichTextWithFX, {
                    __framer__animate: { transition: transition3 },
                    __framer__animateOnce: true,
                    __framer__enter: animation6,
                    __framer__exit: animation7,
                    __framer__styleAppearEffectEnabled: true,
                    __framer__threshold: 0,
                    __fromCanvasComponent: true,
                    __perspectiveFX: false,
                    __targetOpacity: 1,
                    children: bP3PRzGIQ,
                    className: "framer-1imbfad",
                    "data-framer-name": "Card Title",
                    fonts: ["GF;Creato Display-500"],
                    stylesPresetsClassNames: {
                      a: "framer-styles-preset-1n9bmm8",
                      blockquote: "framer-styles-preset-1fw6dnv",
                      h1: "framer-styles-preset-18tf0iw",
                      h2: "framer-styles-preset-b4fewl",
                      h3: "framer-styles-preset-176ky7y",
                      p: "framer-styles-preset-7k06ux",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                    __framer__animate: { transition: transition3 },
                    __framer__animateOnce: true,
                    __framer__enter: animation6,
                    __framer__exit: animation7,
                    __framer__styleAppearEffectEnabled: true,
                    __framer__threshold: 0,
                    __perspectiveFX: false,
                    __targetOpacity: 1,
                    className: "framer-1wubohk",
                    "data-framer-name": "Post Details",
                    children: [
                      /*#__PURE__*/ _jsxs("div", {
                        className: "framer-192fzlu",
                        "data-framer-name": "Details Row",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-1iro191",
                                "data-styles-preset": "yV61UC4Uw",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                },
                                children: "Time to Read:",
                              }),
                            }),
                            className: "framer-1x9jwhr",
                            "data-framer-name": "Detail Label",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-7k06ux",
                                "data-styles-preset": "Gb9Urlcot",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                },
                                children: "3 min read",
                              }),
                            }),
                            className: "framer-umdvi0",
                            "data-framer-name": "Detail",
                            fonts: ["Inter"],
                            text: textContent,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx("div", {
                        className: "framer-1yqh0bd",
                        "data-framer-name": "Line",
                      }),
                      /*#__PURE__*/ _jsxs("div", {
                        className: "framer-18c89qw",
                        "data-framer-name": "Details Row",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-1iro191",
                                "data-styles-preset": "yV61UC4Uw",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                },
                                children: "Category:",
                              }),
                            }),
                            className: "framer-1dl5q2o",
                            "data-framer-name": "Detail Label",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-7k06ux",
                                "data-styles-preset": "Gb9Urlcot",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                },
                                children: "Oral Health Tips",
                              }),
                            }),
                            className: "framer-1117iut",
                            "data-framer-name": "Detail",
                            fonts: ["Inter"],
                            text: YLMlynKkk,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx("div", {
                        className: "framer-1vjn7w2",
                        "data-framer-name": "Line",
                      }),
                      /*#__PURE__*/ _jsxs("div", {
                        className: "framer-a4uipm",
                        "data-framer-name": "Details Row",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-1iro191",
                                "data-styles-preset": "yV61UC4Uw",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                },
                                children: "Date:",
                              }),
                            }),
                            className: "framer-4ur5ee",
                            "data-framer-name": "Detail Label",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-7k06ux",
                                "data-styles-preset": "Gb9Urlcot",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                },
                                children: "June 20, 2026",
                              }),
                            }),
                            className: "framer-1oocc9e",
                            "data-framer-name": "Detail",
                            fonts: ["Inter"],
                            text: /*#__PURE__*/ _jsx("time", {
                              dateTime: updatedAt,
                              children: textContent1,
                            }),
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx("div", {
                        className: "framer-ohzhyo",
                        "data-framer-name": "Line",
                      }),
                      /*#__PURE__*/ _jsxs("div", {
                        className: "framer-7kl3xd",
                        "data-framer-name": "Share Row",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx("p", {
                                className: "framer-styles-preset-1iro191",
                                "data-styles-preset": "yV61UC4Uw",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                },
                                children: "Share:",
                              }),
                            }),
                            className: "framer-qbq6a5",
                            "data-framer-name": "Detail Label",
                            fonts: ["Inter"],
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(Container, {
                              className: "framer-1i5iwvy-container",
                              isAuthoredByUser: true,
                              isModuleExternal: true,
                              nodeId: "u7bRak_QW",
                              scopeId: "Av0juBD09",
                              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                  ntG6bbQkW: {
                                    horizontalSpacing: 8,
                                    styleProperties: {
                                      buttonHeight: 32,
                                      buttonWidth: 32,
                                      radius: 8,
                                    },
                                  },
                                },
                                children: /*#__PURE__*/ _jsx(
                                  SocialShareButtons,
                                  {
                                    advancedColors: {
                                      bufferColor: "rgb(22, 142, 234)",
                                      emailColor: "rgb(212, 70, 56)",
                                      facebookColor:
                                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                      flipboardColor: "rgb(225, 40, 40)",
                                      instagramColor: "rgb(238, 58, 124)",
                                      lineColor: "rgb(0, 195, 0)",
                                      linkedInColor:
                                        "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                                      mastodonColor: "rgb(90, 90, 163)",
                                      pinterestColor: "rgb(230, 0, 25)",
                                      pocketColor: "rgb(239, 64, 86)",
                                      redditColor: "rgb(255, 69, 0)",
                                      snapchatColor: "rgb(255, 252, 0)",
                                      telegramColor: "rgb(0, 136, 204)",
                                      tumblrColor: "rgb(54, 70, 93)",
                                      twitterColor:
                                        "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                      vkColor: "rgb(0, 119, 255)",
                                      weiboColor: "rgb(230, 22, 45)",
                                      whatsappColor: "rgb(37, 211, 102)",
                                      xingColor: "rgb(0, 101, 103)",
                                      youtubeColor: "rgb(255, 3, 2)",
                                    },
                                    font: {},
                                    height: "100%",
                                    horizontalSpacing: 16,
                                    id: "u7bRak_QW",
                                    layoutId: "u7bRak_QW",
                                    platforms: [
                                      "Twitter",
                                      "Facebook",
                                      "LinkedIn",
                                    ],
                                    showText: false,
                                    styleProperties: {
                                      buttonHeight: 50,
                                      buttonWidth: 50,
                                      radius: 8,
                                    },
                                    textColor:
                                      "var(--token-9f10c85b-2edf-4ef9-96e0-f3e6553d041f, rgb(238, 242, 253))",
                                    width: "100%",
                                  }
                                ),
                              }),
                            }),
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx("div", {
                        className: "framer-4znth1",
                        "data-framer-name": "Line",
                      }),
                    ],
                  }),
                ],
              }),
            }),
            /*#__PURE__*/ _jsx(PropertyOverrides, {
              breakpoint: baseVariant,
              overrides: {
                ntG6bbQkW: { y: (componentViewport?.y || 0) + 0 + 1768.2 },
                y3zZhMkVk: { y: (componentViewport?.y || 0) + 0 + 1853.2 },
              },
              children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 1216,
                width: componentViewport?.width || "100vw",
                y: (componentViewport?.y || 0) + 0 + 1306,
                children: /*#__PURE__*/ _jsx(Container, {
                  className: "framer-1i2c9an-container",
                  layout: motionLayout,
                  nodeId: "h6fIfHXG7",
                  scopeId: "Av0juBD09",
                  children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      ntG6bbQkW: { variant: matchVariant("t2zBn0xVU") },
                      y3zZhMkVk: { variant: matchVariant("FCNMlRrs0") },
                    },
                    children: /*#__PURE__*/ _jsx(FAQSection, {
                      height: "100%",
                      id: "h6fIfHXG7",
                      layoutId: "h6fIfHXG7",
                      style: { width: "100%" },
                      variant: matchVariant("LQf0My7Ir"),
                      width: "100%",
                    }),
                  }),
                }),
              }),
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  ".framer-SzEVH.framer-vz28az, .framer-SzEVH .framer-vz28az { display: block; }",
  ".framer-SzEVH.framer-12i5nu7 { align-content: center; align-items: center; background-color: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, #faf9ff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-SzEVH .framer-e86ide { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 210px 30px 0px 30px; position: relative; width: 100%; z-index: 1; }",
  ".framer-SzEVH .framer-kaidz1 { background: linear-gradient(180deg, var(--token-b792d557-4853-49ac-865a-1d8073a4ab4e, rgba(174, 220, 253, 0.6)) 0%, rgba(251, 250, 255, 0) 100%); bottom: 0px; flex: none; gap: 40px; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 100%; }",
  ".framer-SzEVH .framer-hwlwi9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 72px; height: min-content; justify-content: flex-start; max-width: 1296px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1eoq2q3 { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: auto; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-SzEVH .framer-19269h9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1gwpquc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-5isyyq-container, .framer-SzEVH .framer-1i5iwvy-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-SzEVH .framer-5n8dse, .framer-SzEVH .framer-1f5cf2w { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-SzEVH .framer-1fddqhe { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-SzEVH .framer-vko9jk { border-bottom-left-radius: 8px; border-bottom-right-radius: 8px; border-top-left-radius: 8px; border-top-right-radius: 8px; flex: none; height: 64px; position: relative; width: 64px; }",
  ".framer-SzEVH .framer-73829r { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-SzEVH .framer-t1v33l, .framer-SzEVH .framer-p813ky, .framer-SzEVH .framer-1x9jwhr, .framer-SzEVH .framer-umdvi0, .framer-SzEVH .framer-1dl5q2o, .framer-SzEVH .framer-1117iut, .framer-SzEVH .framer-4ur5ee, .framer-SzEVH .framer-1oocc9e, .framer-SzEVH .framer-qbq6a5 { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-SzEVH .framer-10tve7r { aspect-ratio: 0.8461538461538461 / 1; border-bottom-left-radius: 16px; border-bottom-right-radius: 16px; border-top-left-radius: 16px; border-top-right-radius: 16px; flex: 1 0 0px; height: auto; max-width: 550px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-SzEVH .framer-1o1gpon { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 72px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 120px 30px 0px 30px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1xewqon { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 86px; height: min-content; justify-content: flex-start; max-width: 1296px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1imbfad { --framer-paragraph-spacing: 0px; flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-SzEVH .framer-1wubohk { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; max-width: 440px; overflow: visible; padding: 0px; position: sticky; top: 110px; width: 1px; z-index: 1; }",
  ".framer-SzEVH .framer-192fzlu, .framer-SzEVH .framer-18c89qw, .framer-SzEVH .framer-a4uipm, .framer-SzEVH .framer-7kl3xd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1yqh0bd, .framer-SzEVH .framer-1vjn7w2, .framer-SzEVH .framer-ohzhyo, .framer-SzEVH .framer-4znth1 { background-color: var(--token-5e421d18-5d17-4869-827f-e8cec0385dad, rgba(10, 15, 50, 0.2)); flex: none; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
  ".framer-SzEVH .framer-1i2c9an-container { flex: none; height: auto; position: relative; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  ...sharedStyle4.css,
  ...sharedStyle5.css,
  ...sharedStyle6.css,
  ...sharedStyle7.css,
  ...sharedStyle8.css,
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-SzEVH.framer-12i5nu7 { width: 810px; } .framer-SzEVH .framer-e86ide { padding: 180px 30px 0px 30px; z-index: unset; } .framer-SzEVH .framer-hwlwi9, .framer-SzEVH .framer-1xewqon { flex-direction: column; gap: 60px; } .framer-SzEVH .framer-1eoq2q3 { align-self: unset; flex: none; gap: 32px; height: min-content; justify-content: center; max-width: 560px; width: 100%; } .framer-SzEVH .framer-10tve7r { flex: none; max-width: unset; width: 100%; } .framer-SzEVH .framer-1o1gpon { padding: 80px 30px 0px 30px; } .framer-SzEVH .framer-1imbfad { flex: none; width: 100%; } .framer-SzEVH .framer-1wubohk { flex: none; max-width: unset; position: relative; top: unset; width: 100%; }}",
  "@media (max-width: 809.98px) { .framer-SzEVH.framer-12i5nu7 { width: 390px; } .framer-SzEVH .framer-e86ide { gap: 40px; padding: 150px 20px 0px 20px; } .framer-SzEVH .framer-hwlwi9 { align-content: center; align-items: center; flex-direction: column; gap: 40px; justify-content: center; } .framer-SzEVH .framer-1eoq2q3 { align-content: center; align-items: center; align-self: unset; flex: none; gap: 32px; height: min-content; justify-content: center; width: 100%; } .framer-SzEVH .framer-19269h9 { align-content: center; align-items: center; justify-content: center; } .framer-SzEVH .framer-1gwpquc, .framer-SzEVH .framer-73829r { align-content: center; align-items: center; } .framer-SzEVH .framer-1fddqhe { flex-direction: column; } .framer-SzEVH .framer-10tve7r { flex: none; max-width: unset; width: 100%; } .framer-SzEVH .framer-1o1gpon { padding: 60px 20px 0px 20px; } .framer-SzEVH .framer-1xewqon { align-content: center; align-items: center; flex-direction: column; gap: 40px; } .framer-SzEVH .framer-1imbfad { flex: none; width: 100%; } .framer-SzEVH .framer-1wubohk { flex: none; gap: 16px; max-width: unset; position: relative; top: unset; width: 100%; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 5723
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"y3zZhMkVk":{"layout":["fixed","auto"]},"ntG6bbQkW":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"BVdDj_lhC":{"pattern":":BVdDj_lhC","name":"nav"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerAv0juBD09 = withCSS(Component, css, "framer-SzEVH");
export default FramerAv0juBD09;
FramerAv0juBD09.displayName = "Blog";
FramerAv0juBD09.defaultProps = { height: 5723, width: 1200 };
addFonts(
  FramerAv0juBD09,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...SectionTagFonts,
    ...SocialShareButtonsFonts,
    ...FAQSectionFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
    ...getFontsFromSharedStyle(sharedStyle4.fonts),
    ...getFontsFromSharedStyle(sharedStyle5.fonts),
    ...getFontsFromSharedStyle(sharedStyle6.fonts),
    ...getFontsFromSharedStyle(sharedStyle7.fonts),
    ...getFontsFromSharedStyle(sharedStyle8.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerAv0juBD09.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const priority = context.priority;
    return runTasksWithYield(
      [
        () =>
          queryCache
            .get(
              detailQuery(
                getWhereExpressionFromPathVariables(
                  context.pathVariables,
                  "Av0juBD09"
                )
              ),
              locale,
              priority
            )
            .preload(),
        () => forwardLoader(SectionTag, {}, context),
        () => forwardLoader(FAQSection, {}, context),
      ],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerAv0juBD09",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1200",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerAcceptsLayoutTemplate: "true",
        framerIntrinsicHeight: "5723",
        framerLayoutTemplateFlowEffect: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"y3zZhMkVk":{"layout":["fixed","auto"]},"ntG6bbQkW":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
        framerResponsiveScreen: "true",
        framerScrollSections:
          '{"BVdDj_lhC":{"pattern":":BVdDj_lhC","name":"nav"}}',
      },
    },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
