// Generated by Framer (4d43e7b)
import { fontStore } from "framer";
fontStore.loadFonts([
  "GF;Playfair Display-italic",
  "GF;Playfair Display-700italic",
  "GF;Playfair Display-700italic",
  "GF;Playfair Display-italic",
]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Playfair Display",
        source: "google",
        style: "italic",
        uiFamilyName: "Playfair Display",
        url: "https://fonts.gstatic.com/s/playfairdisplay/v40/nuFRD-vYSZviVYUb_rj3ij__anPXDTnCjmHKM4nYO7KN_qiTbtPK-F2rA0s.woff2",
        weight: "400",
      },
      {
        cssFamilyName: "Playfair Display",
        source: "google",
        style: "italic",
        uiFamilyName: "Playfair Display",
        url: "https://fonts.gstatic.com/s/playfairdisplay/v40/nuFRD-vYSZviVYUb_rj3ij__anPXDTnCjmHKM4nYO7KN_k-UbtPK-F2rA0s.woff2",
        weight: "700",
      },
    ],
  },
];
export const css = [
  '.framer-tWSZe .framer-styles-preset-1h8c9zs:not(.rich-text-wrapper), .framer-tWSZe .framer-styles-preset-1h8c9zs.rich-text-wrapper h1 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 80px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -2px; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, #0a0f32); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-tWSZe .framer-styles-preset-1h8c9zs:not(.rich-text-wrapper), .framer-tWSZe .framer-styles-preset-1h8c9zs.rich-text-wrapper h1 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 60px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -2px; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, #0a0f32); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-tWSZe .framer-styles-preset-1h8c9zs:not(.rich-text-wrapper), .framer-tWSZe .framer-styles-preset-1h8c9zs.rich-text-wrapper h1 { --framer-font-family: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-bold-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-family-italic: "Playfair Display", "Playfair Display Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: italic; --framer-font-style-bold: italic; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -2px; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, #0a0f32); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; } }',
];
export const className = "framer-tWSZe";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
