// Generated by Framer (1a21bd5)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const otNFWPuoI = undefined;
const mask =
  'url(\'data:image/svg+xml,<svg display="block" id="407061500" role="presentation" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M 0.781 10.766 C 0.581 10.766 0.381 10.689 0.229 10.537 C -0.076 10.232 -0.076 9.737 0.229 9.432 L 9.432 0.229 C 9.737 -0.076 10.232 -0.076 10.537 0.229 C 10.842 0.534 10.842 1.028 10.537 1.334 L 1.333 10.537 C 1.181 10.689 0.981 10.766 0.781 10.766 Z" fill="var(--1ainiew, rgb(20,116,214))" height="10.76566px" id="xkClOSVk4" transform="translate(2.617 2.617)" width="10.765948888888873px"/><path d="M 9.984 10.766 C 9.784 10.766 9.584 10.69 9.432 10.537 L 0.229 1.334 C -0.076 1.029 -0.076 0.534 0.229 0.229 C 0.534 -0.076 1.028 -0.076 1.334 0.229 L 10.537 9.432 C 10.842 9.737 10.842 10.232 10.537 10.537 C 10.384 10.69 10.184 10.766 9.984 10.766 Z" fill="var(--1ainiew, rgb(20,116,214))" height="10.765911111111112px" id="lFzHJWMch" transform="translate(2.617 2.617)" width="10.765948888888873px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ color, height, id, width, ...props }) => {
  return {
    ...props,
    otNFWPuoI: color ?? props.otNFWPuoI ?? "rgb(20, 116, 214)",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, otNFWPuoI, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-RKEWr", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--1ainiew": otNFWPuoI, ...style },
  });
});
const css = [
  `.framer-RKEWr { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--1ainiew); mask: ${mask}; width: 16px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 16
 * @framerIntrinsicHeight 16
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"otNFWPuoI":"color"}
 * @framerImmutableVariables true
 * @framerVector {"name":"cross-button 1","color":{"type":"variable","value":"1ainiew"},"set":{"localId":"vectorSet/DLVYEDHxh","id":"DLVYEDHxh","moduleId":"H03uyQ6iKrzXYyHfcrbS"}}
 */ const Icon = withCSS(Component, css, "framer-RKEWr");
Icon.displayName = "cross-button 1";
export default Icon;
addPropertyControls(Icon, {
  otNFWPuoI: {
    defaultValue: "rgb(20, 116, 214)",
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerContractVersion: "1",
        framerVariables: '{"otNFWPuoI":"color"}',
        framerVector:
          '{"name":"cross-button 1","color":{"type":"variable","value":"1ainiew"},"set":{"localId":"vectorSet/DLVYEDHxh","id":"DLVYEDHxh","moduleId":"H03uyQ6iKrzXYyHfcrbS"}}',
        framerIntrinsicWidth: "16",
        framerIntrinsicHeight: "16",
        framerSupportedLayoutHeight: "any-prefer-fixed",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
