// Generated by Framer (4f63079)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/fk6IW0hN44iDIbsmKF3a/yd7iafobyNdXrl2a0V9M/ILq5RyVfl.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/UqtXQCViTtsu1vbFZs4w/n0nA0mPhFzPRX0iY7cco/N_TgVO6x4.js";
import * as sharedStyle from "https://framerusercontent.com/modules/TAbCb7DbtTwpZTp75ySa/XDsHE9EApsaKA5nUeCIu/yV61UC4Uw.js";
const cycleOrder = ["vtwqmY2a8", "ASeuEQGnt"];
const serializationHash = "framer-6Re7O";
const variantClassNames = {
  ASeuEQGnt: "framer-v-1nncaaf",
  vtwqmY2a8: "framer-v-iuz61r",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const xpMwkEjaN = undefined;
const a_xKE9DXI = undefined;
const I2LofxTzF = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "vtwqmY2a8",
  "Variant 2": "ASeuEQGnt",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, serial, text, title, width, ...props }) => {
  return {
    ...props,
    a_xKE9DXI: title ?? props.a_xKE9DXI ?? "Cavities",
    I2LofxTzF:
      text ??
      props.I2LofxTzF ??
      "Tooth decay creates holes and causes tooth pain.",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "vtwqmY2a8",
    xpMwkEjaN: serial ?? props.xpMwkEjaN ?? "01",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    xpMwkEjaN,
    a_xKE9DXI,
    I2LofxTzF,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "vtwqmY2a8",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-iuz61r",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "vtwqmY2a8",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { ASeuEQGnt: { "data-framer-name": "Variant 2" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-sszcc3",
              "data-framer-name": "Serial",
              layoutDependency: layoutDependency,
              layoutId: "p6FbnKUef",
              style: {
                backgroundColor:
                  "var(--token-73b66216-b475-415b-b4b6-227679c18659, rgb(195, 230, 255))",
                borderBottomLeftRadius: 30,
                borderBottomRightRadius: 30,
                borderTopLeftRadius: 30,
                borderTopRightRadius: 30,
              },
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1iro191",
                    "data-styles-preset": "yV61UC4Uw",
                    dir: "auto",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                    },
                    children: "01",
                  }),
                }),
                className: "framer-padi8y",
                "data-framer-name": "01",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "ZhdeIgy0C",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                  "--framer-paragraph-spacing": "0px",
                },
                text: xpMwkEjaN,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1065ygm",
              "data-framer-name": "Title",
              layoutDependency: layoutDependency,
              layoutId: "p2KX6w4h8",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-yd8c4f",
                      "data-styles-preset": "ILq5RyVfl",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                      },
                      children: "Cavities",
                    }),
                  }),
                  className: "framer-1m6t4d1",
                  "data-framer-name": "Cavities",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "YCppvEQ7O",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: a_xKE9DXI,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      ASeuEQGnt: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-yd8c4f",
                            "data-styles-preset": "ILq5RyVfl",
                            dir: "auto",
                            style: {
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                            },
                            children: "Cavities",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1izoxyw",
                      "data-styles-preset": "N_TgVO6x4",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                      },
                      children:
                        "Tooth decay creates holes and causes tooth pain.",
                    }),
                  }),
                  className: "framer-12zqejg",
                  "data-framer-name":
                    "Tooth decay creates holes and causes tooth pain.",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "rpvZSNcbT",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: I2LofxTzF,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      ASeuEQGnt: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1izoxyw",
                            "data-styles-preset": "N_TgVO6x4",
                            dir: "auto",
                            style: {
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                            },
                            children:
                              "Tooth decay creates holes and causes tooth pain.",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-6Re7O.framer-1hmi78h, .framer-6Re7O .framer-1hmi78h { display: block; }",
  ".framer-6Re7O.framer-iuz61r { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 195px; }",
  ".framer-6Re7O .framer-sszcc3 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: visible; padding: 15px 19px 15px 19px; position: relative; width: 60px; }",
  ".framer-6Re7O .framer-padi8y { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-6Re7O .framer-1065ygm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-6Re7O .framer-1m6t4d1, .framer-6Re7O .framer-12zqejg { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-6Re7O.framer-v-1nncaaf.framer-iuz61r { align-content: center; align-items: center; justify-content: center; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 168
 * @framerIntrinsicWidth 195
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ASeuEQGnt":{"layout":["fixed","auto"]}}}
 * @framerVariables {"xpMwkEjaN":"serial","a_xKE9DXI":"title","I2LofxTzF":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerP4F5DjLJn = withCSS(Component, css, "framer-6Re7O");
export default FramerP4F5DjLJn;
FramerP4F5DjLJn.displayName = "Problem Wrap";
FramerP4F5DjLJn.defaultProps = { height: 168, width: 195 };
addPropertyControls(FramerP4F5DjLJn, {
  variant: {
    options: ["vtwqmY2a8", "ASeuEQGnt"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
  xpMwkEjaN: {
    defaultValue: "01",
    displayTextArea: false,
    title: "Serial",
    type: ControlType.String,
  },
  onxpMwkEjaNChange: { changes: "xpMwkEjaN", type: ControlType.ChangeHandler },
  a_xKE9DXI: {
    defaultValue: "Cavities",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  ona_xKE9DXIChange: { changes: "a_xKE9DXI", type: ControlType.ChangeHandler },
  I2LofxTzF: {
    defaultValue: "Tooth decay creates holes and causes tooth pain.",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  onI2LofxTzFChange: { changes: "I2LofxTzF", type: ControlType.ChangeHandler },
});
addFonts(
  FramerP4F5DjLJn,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerP4F5DjLJn",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "195",
        framerAutoSizeImages: "true",
        framerVariables:
          '{"xpMwkEjaN":"serial","a_xKE9DXI":"title","I2LofxTzF":"text"}',
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ASeuEQGnt":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "168",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./P4F5DjLJn.map
