// Generated by Framer (27c13c3)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FAQ from "https://framerusercontent.com/modules/3xjgGIxWykszG8vW0kIU/8t7vKB9lxQeuCPFMDMsn/AMM2wMD7E.js";
const FAQFonts = getFonts(FAQ);
const cycleOrder = [
  "y_KLncpvG",
  "y6UkJH5_j",
  "K_aJRbJQa",
  "KxA8YsYVb",
  "y_6ryULIO",
  "YiR6mZWJW",
  "MlbxF7luD",
  "ortoo2cBd",
  "jJIPzm3sG",
  "Yoq1Gnp50",
];
const serializationHash = "framer-CEDnX";
const variantClassNames = {
  jJIPzm3sG: "framer-v-85gf9h",
  K_aJRbJQa: "framer-v-1armq4a",
  KxA8YsYVb: "framer-v-it8wpz",
  MlbxF7luD: "framer-v-1i78r1l",
  ortoo2cBd: "framer-v-1803on1",
  y_6ryULIO: "framer-v-1bw1ujl",
  y_KLncpvG: "framer-v-1g5qkib",
  y6UkJH5_j: "framer-v-1dn07tg",
  YiR6mZWJW: "framer-v-177rgio",
  Yoq1Gnp50: "framer-v-x6d5w",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const transition2 = {
  delay: 0,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Desktop 2": "y6UkJH5_j",
  "Desktop 3": "K_aJRbJQa",
  "Desktop 4": "KxA8YsYVb",
  "Desktop 5": "y_6ryULIO",
  Desktop: "y_KLncpvG",
  Phone: "Yoq1Gnp50",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "y_KLncpvG",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "y_KLncpvG",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const zcnlP3cHozsvo9r = activeVariantCallback(async (...args) => {
    setVariant("y_KLncpvG");
  });
  const zcnlP3cHo90sxi9 = activeVariantCallback(async (...args) => {
    setVariant("YiR6mZWJW");
  });
  const zcnlP3cHo1x4riap = activeVariantCallback(async (...args) => {
    setVariant("y6UkJH5_j");
  });
  const zcnlP3cHo152r5d9 = activeVariantCallback(async (...args) => {
    setVariant("MlbxF7luD");
  });
  const zcnlP3cHowqs202 = activeVariantCallback(async (...args) => {
    setVariant("K_aJRbJQa");
  });
  const zcnlP3cHomufo8g = activeVariantCallback(async (...args) => {
    setVariant("ortoo2cBd");
  });
  const zcnlP3cHoki337e = activeVariantCallback(async (...args) => {
    setVariant("KxA8YsYVb");
  });
  const zcnlP3cHovxd4bf = activeVariantCallback(async (...args) => {
    setVariant("jJIPzm3sG");
  });
  const zcnlP3cHollgyb3 = activeVariantCallback(async (...args) => {
    setVariant("y_6ryULIO");
  });
  const zcnlP3cHoahvola = activeVariantCallback(async (...args) => {
    setVariant("Yoq1Gnp50");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          {
            jJIPzm3sG: { value: transition2 },
            MlbxF7luD: { value: transition2 },
            ortoo2cBd: { value: transition2 },
            YiR6mZWJW: { value: transition2 },
            Yoq1Gnp50: { value: transition2 },
          },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1g5qkib",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "y_KLncpvG",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              jJIPzm3sG: { "data-framer-name": "Phone" },
              K_aJRbJQa: { "data-framer-name": "Desktop 3" },
              KxA8YsYVb: { "data-framer-name": "Desktop 4" },
              MlbxF7luD: { "data-framer-name": "Phone" },
              ortoo2cBd: { "data-framer-name": "Phone" },
              y_6ryULIO: { "data-framer-name": "Desktop 5" },
              y6UkJH5_j: { "data-framer-name": "Desktop 2" },
              YiR6mZWJW: { "data-framer-name": "Phone" },
              Yoq1Gnp50: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 162,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 0,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1xvhkf4-container",
                layoutDependency: layoutDependency,
                layoutId: "Om12Y_VD0-container",
                nodeId: "Om12Y_VD0",
                rendersWithMotion: true,
                scopeId: "F5lt3TRyI",
                children: /*#__PURE__*/ _jsx(FAQ, {
                  height: "100%",
                  id: "Om12Y_VD0",
                  JLmDk5xC1:
                    "Most people benefit from a routine dental checkup and cleaning every six months. Your dentist may recommend more frequent visits based on your individual oral-health needs.",
                  l9w6fZfcZ:
                    "How often should I visit the dentist for checkups?",
                  layoutId: "Om12Y_VD0",
                  style: { width: "100%" },
                  variant: matchVariant("fPcsuYzT2"),
                  width: "100%",
                  zcnlP3cHo: zcnlP3cHozsvo9r,
                  ...addPropertyOverrides(
                    {
                      jJIPzm3sG: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo90sxi9,
                      },
                      K_aJRbJQa: { variant: matchVariant("LgvFedpXj") },
                      KxA8YsYVb: { variant: matchVariant("LgvFedpXj") },
                      MlbxF7luD: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo90sxi9,
                      },
                      ortoo2cBd: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo90sxi9,
                      },
                      y_6ryULIO: { variant: matchVariant("LgvFedpXj") },
                      y6UkJH5_j: { variant: matchVariant("LgvFedpXj") },
                      YiR6mZWJW: {
                        variant: matchVariant("PbZoKNxhu"),
                        zcnlP3cHo: zcnlP3cHo90sxi9,
                      },
                      Yoq1Gnp50: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo90sxi9,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 162,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 178,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-ftr807-container",
                layoutDependency: layoutDependency,
                layoutId: "SIoXtFmm_-container",
                nodeId: "SIoXtFmm_",
                rendersWithMotion: true,
                scopeId: "F5lt3TRyI",
                children: /*#__PURE__*/ _jsx(FAQ, {
                  height: "100%",
                  id: "SIoXtFmm_",
                  JLmDk5xC1:
                    "Brush twice daily with fluoride toothpaste, clean between your teeth every day, limit sugary snacks and drinks, and keep up with regular dental checkups.",
                  l9w6fZfcZ:
                    "What can I do to prevent tooth decay effectively?",
                  layoutId: "SIoXtFmm_",
                  style: { width: "100%" },
                  variant: matchVariant("LgvFedpXj"),
                  width: "100%",
                  zcnlP3cHo: zcnlP3cHo1x4riap,
                  ...addPropertyOverrides(
                    {
                      jJIPzm3sG: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo152r5d9,
                      },
                      MlbxF7luD: {
                        variant: matchVariant("PbZoKNxhu"),
                        zcnlP3cHo: undefined,
                      },
                      ortoo2cBd: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo152r5d9,
                      },
                      y6UkJH5_j: { variant: matchVariant("fPcsuYzT2") },
                      YiR6mZWJW: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo152r5d9,
                      },
                      Yoq1Gnp50: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHo152r5d9,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 162,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 356,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-14vw832-container",
                layoutDependency: layoutDependency,
                layoutId: "rldFgK966-container",
                nodeId: "rldFgK966",
                rendersWithMotion: true,
                scopeId: "F5lt3TRyI",
                children: /*#__PURE__*/ _jsx(FAQ, {
                  height: "100%",
                  id: "rldFgK966",
                  JLmDk5xC1:
                    "Yes. Professional cleanings remove hardened plaque and tartar that brushing alone cannot reach, helping lower the risk of cavities, gum disease, and bad breath.",
                  l9w6fZfcZ:
                    "Are professional teeth cleanings necessary for oral health?",
                  layoutId: "rldFgK966",
                  style: { width: "100%" },
                  variant: matchVariant("LgvFedpXj"),
                  width: "100%",
                  zcnlP3cHo: zcnlP3cHowqs202,
                  ...addPropertyOverrides(
                    {
                      jJIPzm3sG: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHomufo8g,
                      },
                      K_aJRbJQa: { variant: matchVariant("fPcsuYzT2") },
                      MlbxF7luD: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHomufo8g,
                      },
                      ortoo2cBd: {
                        variant: matchVariant("PbZoKNxhu"),
                        zcnlP3cHo: undefined,
                      },
                      YiR6mZWJW: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHomufo8g,
                      },
                      Yoq1Gnp50: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHomufo8g,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 162,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 534,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-52c033-container",
                layoutDependency: layoutDependency,
                layoutId: "eD6za5ZjL-container",
                nodeId: "eD6za5ZjL",
                rendersWithMotion: true,
                scopeId: "F5lt3TRyI",
                children: /*#__PURE__*/ _jsx(FAQ, {
                  height: "100%",
                  id: "eD6za5ZjL",
                  JLmDk5xC1:
                    "Your first visit usually includes a review of your health history, an examination of your teeth and gums, possible X-rays, and time to discuss any concerns or treatment options.",
                  l9w6fZfcZ:
                    "What should I expect during my first dental appointment?",
                  layoutId: "eD6za5ZjL",
                  style: { width: "100%" },
                  variant: matchVariant("LgvFedpXj"),
                  width: "100%",
                  zcnlP3cHo: zcnlP3cHoki337e,
                  ...addPropertyOverrides(
                    {
                      jJIPzm3sG: {
                        variant: matchVariant("PbZoKNxhu"),
                        zcnlP3cHo: undefined,
                      },
                      KxA8YsYVb: { variant: matchVariant("fPcsuYzT2") },
                      MlbxF7luD: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHovxd4bf,
                      },
                      ortoo2cBd: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHovxd4bf,
                      },
                      YiR6mZWJW: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHovxd4bf,
                      },
                      Yoq1Gnp50: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHovxd4bf,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 162,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 712,
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-14sm2bg-container",
                layoutDependency: layoutDependency,
                layoutId: "cEZEp3vkZ-container",
                nodeId: "cEZEp3vkZ",
                rendersWithMotion: true,
                scopeId: "F5lt3TRyI",
                children: /*#__PURE__*/ _jsx(FAQ, {
                  height: "100%",
                  id: "cEZEp3vkZ",
                  JLmDk5xC1:
                    "Brush gently along the gumline twice a day, floss or use interdental cleaners daily, eat a balanced diet, and book a dental visit if you notice bleeding, swelling, or sensitivity.",
                  l9w6fZfcZ: "How can I keep my gums healthy every day?",
                  layoutId: "cEZEp3vkZ",
                  style: { width: "100%" },
                  variant: matchVariant("LgvFedpXj"),
                  width: "100%",
                  zcnlP3cHo: zcnlP3cHollgyb3,
                  ...addPropertyOverrides(
                    {
                      jJIPzm3sG: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHoahvola,
                      },
                      MlbxF7luD: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHoahvola,
                      },
                      ortoo2cBd: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHoahvola,
                      },
                      y_6ryULIO: { variant: matchVariant("fPcsuYzT2") },
                      YiR6mZWJW: {
                        variant: matchVariant("RNtBbzc1n"),
                        zcnlP3cHo: zcnlP3cHoahvola,
                      },
                      Yoq1Gnp50: {
                        variant: matchVariant("PbZoKNxhu"),
                        zcnlP3cHo: undefined,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-CEDnX.framer-1egd88a, .framer-CEDnX .framer-1egd88a { display: block; }",
  ".framer-CEDnX.framer-1g5qkib { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 700px; }",
  ".framer-CEDnX .framer-1xvhkf4-container, .framer-CEDnX .framer-ftr807-container, .framer-CEDnX .framer-14vw832-container, .framer-CEDnX .framer-52c033-container, .framer-CEDnX .framer-14sm2bg-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-CEDnX.framer-v-177rgio.framer-1g5qkib, .framer-CEDnX.framer-v-1i78r1l.framer-1g5qkib, .framer-CEDnX.framer-v-1803on1.framer-1g5qkib, .framer-CEDnX.framer-v-85gf9h.framer-1g5qkib, .framer-CEDnX.framer-v-x6d5w.framer-1g5qkib { width: 390px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 662
 * @framerIntrinsicWidth 700
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"y6UkJH5_j":{"layout":["fixed","auto"]},"K_aJRbJQa":{"layout":["fixed","auto"]},"KxA8YsYVb":{"layout":["fixed","auto"]},"y_6ryULIO":{"layout":["fixed","auto"]},"YiR6mZWJW":{"layout":["fixed","auto"]},"MlbxF7luD":{"layout":["fixed","auto"]},"ortoo2cBd":{"layout":["fixed","auto"]},"jJIPzm3sG":{"layout":["fixed","auto"]},"Yoq1Gnp50":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerF5lt3TRyI = withCSS(Component, css, "framer-CEDnX");
export default FramerF5lt3TRyI;
FramerF5lt3TRyI.displayName = "FAQs";
FramerF5lt3TRyI.defaultProps = { height: 662, width: 700 };
addPropertyControls(FramerF5lt3TRyI, {
  variant: {
    options: [
      "y_KLncpvG",
      "y6UkJH5_j",
      "K_aJRbJQa",
      "KxA8YsYVb",
      "y_6ryULIO",
      "YiR6mZWJW",
      "MlbxF7luD",
      "ortoo2cBd",
      "jJIPzm3sG",
      "Yoq1Gnp50",
    ],
    optionTitles: [
      "Desktop",
      "Desktop 2",
      "Desktop 3",
      "Desktop 4",
      "Desktop 5",
      "Phone",
      "Phone",
      "Phone",
      "Phone",
      "Phone",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerF5lt3TRyI, [{ explicitInter: true, fonts: [] }, ...FAQFonts], {
  supportsExplicitInterCodegen: true,
});
FramerF5lt3TRyI.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(FAQ, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerF5lt3TRyI",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "700",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"y6UkJH5_j":{"layout":["fixed","auto"]},"K_aJRbJQa":{"layout":["fixed","auto"]},"KxA8YsYVb":{"layout":["fixed","auto"]},"y_6ryULIO":{"layout":["fixed","auto"]},"YiR6mZWJW":{"layout":["fixed","auto"]},"MlbxF7luD":{"layout":["fixed","auto"]},"ortoo2cBd":{"layout":["fixed","auto"]},"jJIPzm3sG":{"layout":["fixed","auto"]},"Yoq1Gnp50":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "662",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
