// Generated by Framer (27c13c3)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/FuJ6X274e31USRrTt70U/kPpP6M7GYKM9iaVV3ucq/glAniD7kb.js";
import * as sharedStyle from "https://framerusercontent.com/modules/zbVJsUpTCk3xtafWDaCn/KykQNbYci2z39MdNYDX1/phrzN361W.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/1kTnJbAmUmWMoOUB3jLm/ToNCtEYglxFrE7OUnpAV/xaK4FL4sA.js";
const cycleOrder = ["JJrZAabq0", "rfdEtewnB"];
const serializationHash = "framer-M7M6j";
const variantClassNames = {
  JJrZAabq0: "framer-v-4j3o4",
  rfdEtewnB: "framer-v-vfbhy8",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const xtNuUN_2k = undefined;
const lSh7IR7dq = undefined;
const xqCFPqQMd = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "JJrZAabq0",
  "Variant 2": "rfdEtewnB",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  contactInformationAddress,
  contactInformationName,
  height,
  id,
  link,
  width,
  ...props
}) => {
  return {
    ...props,
    lSh7IR7dq: link ?? props.lSh7IR7dq,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "JJrZAabq0",
    xqCFPqQMd:
      contactInformationAddress ?? props.xqCFPqQMd ?? "+1 (212) 555-0198",
    xtNuUN_2k: contactInformationName ?? props.xtNuUN_2k ?? "Phone",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    xtNuUN_2k,
    xqCFPqQMd,
    lSh7IR7dq,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "JJrZAabq0",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-4j3o4",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "JJrZAabq0",
          ref: refBinding,
          style: {
            background:
              "linear-gradient(180deg, var(--token-b792d557-4853-49ac-865a-1d8073a4ab4e, rgba(174, 220, 253, 0.6)) 0%, var(--token-6d18c731-5ef4-4071-9be6-7c4310ed2688, rgba(174, 220, 253, 0.3)) 100%)",
            borderBottomLeftRadius: 16,
            borderBottomRightRadius: 16,
            borderTopLeftRadius: 16,
            borderTopRightRadius: 16,
            ...style,
          },
          ...addPropertyOverrides(
            { rfdEtewnB: { "data-framer-name": "Variant 2" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1pjf6bk",
            "data-framer-name": "COntainer",
            layoutDependency: layoutDependency,
            layoutId: "shrGSdAjK",
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-ne5fgw",
                    "data-styles-preset": "phrzN361W",
                    dir: "auto",
                    style: {
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                    },
                    children: "Phone",
                  }),
                }),
                className: "framer-113z1p4",
                "data-framer-name": "Card Title",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "BpEdBEyGo",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                  "--framer-paragraph-spacing": "0px",
                },
                text: xtNuUN_2k,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1046r05",
                    "data-styles-preset": "glAniD7kb",
                    dir: "auto",
                    style: {
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                    },
                    children: /*#__PURE__*/ _jsx(Link, {
                      href: lSh7IR7dq,
                      motionChild: true,
                      nodeId: "S1fooccQC",
                      openInNewTab: true,
                      preserveParams: false,
                      relValues: [],
                      scopeId: "dIacV0Vyw",
                      smoothScroll: false,
                      children: /*#__PURE__*/ _jsx(motion.a, {
                        className: "framer-styles-preset-1n9bmm8",
                        "data-styles-preset": "xaK4FL4sA",
                        children: "+1 (212) 555-0198",
                      }),
                    }),
                  }),
                }),
                className: "framer-wog9oz",
                "data-framer-name": "Card Detail",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "S1fooccQC",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                  "--framer-paragraph-spacing": "0px",
                },
                text: xqCFPqQMd,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-M7M6j.framer-m9twbg, .framer-M7M6j .framer-m9twbg { display: block; }",
  ".framer-M7M6j.framer-4j3o4 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 66px 50px 66px 50px; position: relative; width: 410px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-M7M6j .framer-1pjf6bk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-M7M6j .framer-113z1p4, .framer-M7M6j .framer-wog9oz { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-M7M6j.framer-v-vfbhy8.framer-4j3o4 { padding: 48px 24px 48px 24px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 410
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"rfdEtewnB":{"layout":["fixed","auto"]}}}
 * @framerVariables {"xtNuUN_2k":"contactInformationName","xqCFPqQMd":"contactInformationAddress","lSh7IR7dq":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerdIacV0Vyw = withCSS(Component, css, "framer-M7M6j");
export default FramerdIacV0Vyw;
FramerdIacV0Vyw.displayName = "Contact Card";
FramerdIacV0Vyw.defaultProps = { height: 200, width: 410 };
addPropertyControls(FramerdIacV0Vyw, {
  variant: {
    options: ["JJrZAabq0", "rfdEtewnB"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
  xtNuUN_2k: {
    defaultValue: "Phone",
    displayTextArea: false,
    title: "Contact Information Name",
    type: ControlType.String,
  },
  onxtNuUN_2kChange: { changes: "xtNuUN_2k", type: ControlType.ChangeHandler },
  xqCFPqQMd: {
    defaultValue: "+1 (212) 555-0198",
    displayTextArea: false,
    title: "Contact Information Address",
    type: ControlType.String,
  },
  onxqCFPqQMdChange: { changes: "xqCFPqQMd", type: ControlType.ChangeHandler },
  lSh7IR7dq: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerdIacV0Vyw,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerdIacV0Vyw",
      slots: [],
      annotations: {
        framerVariables:
          '{"xtNuUN_2k":"contactInformationName","xqCFPqQMd":"contactInformationAddress","lSh7IR7dq":"link"}',
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "200",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "410",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"rfdEtewnB":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
