// Generated by Framer (625f89c)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-Mh3yM .framer-styles-preset-1n9bmm8:not(.rich-text-wrapper), .framer-Mh3yM .framer-styles-preset-1n9bmm8.rich-text-wrapper a { --framer-link-hover-text-color: var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, #0a0f32); transition-delay: 0s; transition-duration: 0.4s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }",
];
export const className = "framer-Mh3yM";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
