// Generated by Framer (f0eed09)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/KFnLzyqEfHDrzezhUflr/Cz0PtD6OeihsVZm3aaH9/c7bg3jEsS.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/3uvUzqtHOpRrr7gJTJhU/YkVGizH00aGbkCUQud7B/Gb9Urlcot.js";
import * as sharedStyle from "https://framerusercontent.com/modules/jmtSiVZwzgXfNgZ4Kww6/gRGrvd9iJRl1g1o6VkOQ/itDzyk8Gn.js";
const enabledGestures = { e8RXliyFR: { hover: true } };
const serializationHash = "framer-IyCxd";
const variantClassNames = { e8RXliyFR: "framer-v-62l7aq" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const sYeXvR2_3 = undefined;
const J8v4upYV3 = undefined;
const PuxqfnTVs = undefined;
const SmyAxoZWU = undefined;
const XS51_8wzp = undefined;
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  catagory,
  exacpt,
  height,
  id,
  image,
  link,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    J8v4upYV3: image ??
      props.J8v4upYV3 ?? {
        alt: "",
        pixelHeight: 1200,
        pixelWidth: 2592,
        src: "https://framerusercontent.com/images/VCHHfe9zesTgHYiyU87cbzXACIY.png?width=2592&height=1200",
        srcSet:
          "https://framerusercontent.com/images/VCHHfe9zesTgHYiyU87cbzXACIY.png?scale-down-to=512&width=2592&height=1200 512w,https://framerusercontent.com/images/VCHHfe9zesTgHYiyU87cbzXACIY.png?scale-down-to=1024&width=2592&height=1200 1024w,https://framerusercontent.com/images/VCHHfe9zesTgHYiyU87cbzXACIY.png?scale-down-to=2048&width=2592&height=1200 2048w,https://framerusercontent.com/images/VCHHfe9zesTgHYiyU87cbzXACIY.png?width=2592&height=1200 2592w",
      },
    PuxqfnTVs: catagory ?? props.PuxqfnTVs ?? "Dental Care :",
    SmyAxoZWU:
      title ??
      props.SmyAxoZWU ??
      "How Regular Dental Visits Help Maintain Strong Healthy Teeth",
    sYeXvR2_3: link ?? props.sYeXvR2_3,
    XS51_8wzp:
      exacpt ??
      props.XS51_8wzp ??
      "Regular checkups detect early problems, prevent decay, and ensure healthy gums and teeth through professional cleaning and expert dental advice.",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    J8v4upYV3,
    PuxqfnTVs,
    SmyAxoZWU,
    XS51_8wzp,
    sYeXvR2_3,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "e8RXliyFR",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: sYeXvR2_3,
          motionChild: true,
          nodeId: "e8RXliyFR",
          openInNewTab: false,
          scopeId: "uiLea2ksj",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-62l7aq",
              className,
              classNames
            )} framer-icqtbp`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "e8RXliyFR",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { "e8RXliyFR-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-nbesoj",
                layoutDependency: layoutDependency,
                layoutId: "OaP795kTQ",
                style: {
                  borderBottomLeftRadius: 16,
                  borderBottomRightRadius: 16,
                  borderTopLeftRadius: 16,
                  borderTopRightRadius: 16,
                },
                children: /*#__PURE__*/ _jsx(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 1200,
                    intrinsicWidth: 2592,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0 + 0
                    ),
                    pixelHeight: 1200,
                    pixelWidth: 2592,
                    sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                    ...toResponsiveImage(J8v4upYV3),
                  },
                  className: "framer-cuv6zl",
                  layoutDependency: layoutDependency,
                  layoutId: "q3eoWL8rz",
                  style: {
                    borderBottomLeftRadius: 16,
                    borderBottomRightRadius: 16,
                    borderTopLeftRadius: 16,
                    borderTopRightRadius: 16,
                    scale: 1,
                  },
                  variants: { "e8RXliyFR-hover": { scale: 1.1 } },
                }),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-vrd4lr",
                "data-framer-name": "Title Wrap",
                layoutDependency: layoutDependency,
                layoutId: "u_XBwRKuB",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-it79c8",
                        "data-styles-preset": "itDzyk8Gn",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                        },
                        children: "Dental Care :",
                      }),
                    }),
                    className: "framer-1blzrim",
                    "data-framer-name": "Title",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "tQ0EFOec1",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: PuxqfnTVs,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-1xzap3v",
                        "data-styles-preset": "c7bg3jEsS",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                        },
                        children:
                          "How Regular Dental Visits Help Maintain Strong Healthy Teeth",
                      }),
                    }),
                    className: "framer-1tgo71v",
                    "data-framer-name": "Subtitle",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "Jx3MphWby",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: SmyAxoZWU,
                    variants: {
                      "e8RXliyFR-hover": {
                        "--extracted-r6o4lv":
                          "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                      },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        "e8RXliyFR-hover": {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1xzap3v",
                              "data-styles-preset": "c7bg3jEsS",
                              dir: "auto",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                              },
                              children:
                                "How Regular Dental Visits Help Maintain Strong Healthy Teeth",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-7k06ux",
                        "data-styles-preset": "Gb9Urlcot",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                        },
                        children:
                          "Regular checkups detect early problems, prevent decay, and ensure healthy gums and teeth through professional cleaning and expert dental advice.",
                      }),
                    }),
                    className: "framer-1wn06go",
                    "data-framer-name": "Body",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "lqYOrbEwc",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: XS51_8wzp,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-IyCxd.framer-icqtbp, .framer-IyCxd .framer-icqtbp { display: block; }",
  ".framer-IyCxd.framer-62l7aq { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1140px; }",
  ".framer-IyCxd .framer-nbesoj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-IyCxd .framer-cuv6zl { aspect-ratio: 2.159090909090909 / 1; flex: 1 0 0px; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-IyCxd .framer-vrd4lr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-IyCxd .framer-1blzrim, .framer-IyCxd .framer-1tgo71v { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-IyCxd .framer-1wn06go { flex: none; height: auto; max-width: 745px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 701
 * @framerIntrinsicWidth 1140
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"lvBJ3hIwg":{"layout":["fixed","auto"]}}}
 * @framerVariables {"J8v4upYV3":"image","PuxqfnTVs":"catagory","SmyAxoZWU":"title","XS51_8wzp":"exacpt","sYeXvR2_3":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameruiLea2ksj = withCSS(Component, css, "framer-IyCxd");
export default FrameruiLea2ksj;
FrameruiLea2ksj.displayName = "Highlight Blog Card";
FrameruiLea2ksj.defaultProps = { height: 701, width: 1140 };
addPropertyControls(FrameruiLea2ksj, {
  J8v4upYV3: {
    __defaultAssetReference:
      "data:framer/asset-reference,VCHHfe9zesTgHYiyU87cbzXACIY.png?originalFilename=Featured+Image.png&width=2592&height=1200",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,VCHHfe9zesTgHYiyU87cbzXACIY.png?originalFilename=Featured+Image.png&width=2592&height=1200",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  PuxqfnTVs: {
    defaultValue: "Dental Care :",
    displayTextArea: false,
    title: "Catagory",
    type: ControlType.String,
  },
  onPuxqfnTVsChange: { changes: "PuxqfnTVs", type: ControlType.ChangeHandler },
  SmyAxoZWU: {
    defaultValue:
      "How Regular Dental Visits Help Maintain Strong Healthy Teeth",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onSmyAxoZWUChange: { changes: "SmyAxoZWU", type: ControlType.ChangeHandler },
  XS51_8wzp: {
    defaultValue:
      "Regular checkups detect early problems, prevent decay, and ensure healthy gums and teeth through professional cleaning and expert dental advice.",
    displayTextArea: false,
    title: "Exacpt",
    type: ControlType.String,
  },
  onXS51_8wzpChange: { changes: "XS51_8wzp", type: ControlType.ChangeHandler },
  sYeXvR2_3: { title: "Link", type: ControlType.Link },
});
addFonts(
  FrameruiLea2ksj,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FrameruiLea2ksj",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"lvBJ3hIwg":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicHeight: "701",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerVariables:
          '{"J8v4upYV3":"image","PuxqfnTVs":"catagory","SmyAxoZWU":"title","XS51_8wzp":"exacpt","sYeXvR2_3":"link"}',
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1140",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./uiLea2ksj.map
