// Generated by Framer (4d43e7b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/fk6IW0hN44iDIbsmKF3a/yd7iafobyNdXrl2a0V9M/ILq5RyVfl.js";
import * as sharedStyle from "https://framerusercontent.com/modules/jmtSiVZwzgXfNgZ4Kww6/gRGrvd9iJRl1g1o6VkOQ/itDzyk8Gn.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/UqtXQCViTtsu1vbFZs4w/n0nA0mPhFzPRX0iY7cco/N_TgVO6x4.js";
import Vector from "https://framerusercontent.com/modules/rOifFgkuixjtn1OpoQZ6/W7wvUTVPI3w2rnsdWW99/Z8vtS7jyO.js";
const VectorFonts = getFonts(Vector);
const enabledGestures = { FwXhQIxKg: { hover: true } };
const cycleOrder = ["FwXhQIxKg", "XqwBjkShH"];
const serializationHash = "framer-LZY9M";
const variantClassNames = {
  FwXhQIxKg: "framer-v-1a6prdx",
  XqwBjkShH: "framer-v-1ip2hgu",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const dgnFtzry_ = undefined;
const DLlH3YBTh = undefined;
const goDSnHjCE = undefined;
const fbgHU7uFD = undefined;
const SLjMvjeE7 = undefined;
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Desktop: "FwXhQIxKg", Phone: "XqwBjkShH" };
const Variants = motion.create(React.Fragment);
const getProps = ({
  height,
  id,
  image,
  link,
  subtitle,
  text,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    dgnFtzry_: link ?? props.dgnFtzry_,
    DLlH3YBTh: title ?? props.DLlH3YBTh ?? "Hygiene :",
    fbgHU7uFD:
      text ??
      props.fbgHU7uFD ??
      "Brushing and flossing daily help keep teeth clean and gums healthy.",
    goDSnHjCE:
      subtitle ??
      props.goDSnHjCE ??
      "Simple Daily Habits for Better Oral Health",
    SLjMvjeE7: image ??
      props.SLjMvjeE7 ?? {
        alt: "",
        pixelHeight: 776,
        pixelWidth: 564,
        src: "https://framerusercontent.com/images/dfy1DIiq37YRVJKtqLtixXpzBk.png?width=564&height=776",
        srcSet:
          "https://framerusercontent.com/images/dfy1DIiq37YRVJKtqLtixXpzBk.png?width=564&height=776 564w",
      },
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "FwXhQIxKg",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    DLlH3YBTh,
    goDSnHjCE,
    fbgHU7uFD,
    SLjMvjeE7,
    dgnFtzry_,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "FwXhQIxKg",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: dgnFtzry_,
          motionChild: true,
          nodeId: "FwXhQIxKg",
          openInNewTab: false,
          scopeId: "oeEWvd_eU",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1a6prdx",
              className,
              classNames
            )} framer-ihkjhl`,
            "data-framer-name": "Desktop",
            layoutDependency: layoutDependency,
            layoutId: "FwXhQIxKg",
            ref: refBinding,
            style: {
              backgroundColor:
                "var(--token-9f10c85b-2edf-4ef9-96e0-f3e6553d041f, rgb(238, 242, 253))",
              borderBottomLeftRadius: 16,
              borderBottomRightRadius: 16,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              ...style,
            },
            ...addPropertyOverrides(
              {
                "FwXhQIxKg-hover": { "data-framer-name": undefined },
                XqwBjkShH: { "data-framer-name": "Phone" },
              },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-17o43no",
              "data-framer-name": "Row",
              layoutDependency: layoutDependency,
              layoutId: "hUyWPwLEf",
              children: [
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-1nj2sfk",
                  "data-framer-name": "Column",
                  layoutDependency: layoutDependency,
                  layoutId: "j11BLdPy0",
                  children: [
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-plzkz6",
                      "data-framer-name": "Column",
                      layoutDependency: layoutDependency,
                      layoutId: "gMYqMY2Ao",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-it79c8",
                              "data-styles-preset": "itDzyk8Gn",
                              dir: "auto",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                              },
                              children: "Hygiene :",
                            }),
                          }),
                          className: "framer-12i2jbv",
                          "data-framer-name": "Title",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "kDAcyXSwY",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          text: DLlH3YBTh,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsxs(motion.div, {
                          className: "framer-jw18uq",
                          "data-framer-name": "Column",
                          layoutDependency: layoutDependency,
                          layoutId: "iC8Q5x6Rn",
                          children: [
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  className: "framer-styles-preset-yd8c4f",
                                  "data-styles-preset": "ILq5RyVfl",
                                  dir: "auto",
                                  style: {
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                                  },
                                  children:
                                    "Simple Daily Habits for Better Oral Health",
                                }),
                              }),
                              className: "framer-15414dl",
                              "data-framer-name": "Subtitle",
                              fonts: ["Inter"],
                              layoutDependency: layoutDependency,
                              layoutId: "faMn4o8HX",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              text: goDSnHjCE,
                              variants: {
                                "FwXhQIxKg-hover": {
                                  "--extracted-r6o4lv":
                                    "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                                },
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                              ...addPropertyOverrides(
                                {
                                  "FwXhQIxKg-hover": {
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          className:
                                            "framer-styles-preset-yd8c4f",
                                          "data-styles-preset": "ILq5RyVfl",
                                          dir: "auto",
                                          style: {
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                                          },
                                          children:
                                            "Simple Daily Habits for Better Oral Health",
                                        }),
                                      }
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  className: "framer-styles-preset-1izoxyw",
                                  "data-styles-preset": "N_TgVO6x4",
                                  dir: "auto",
                                  style: {
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                                  },
                                  children:
                                    "Brushing and flossing daily help keep teeth clean and gums healthy.",
                                }),
                              }),
                              className: "framer-1j7ou8j",
                              "data-framer-name": "Body",
                              fonts: ["Inter"],
                              layoutDependency: layoutDependency,
                              layoutId: "dggzD4NA3",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                                "--framer-paragraph-spacing": "0px",
                              },
                              text: fbgHU7uFD,
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          ],
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-10nguj4",
                      "data-framer-name": "Button",
                      layoutDependency: layoutDependency,
                      layoutId: "OStXuOOK2",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-it79c8",
                              "data-styles-preset": "itDzyk8Gn",
                              dir: "auto",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213)))",
                              },
                              children: "Learn More",
                            }),
                          }),
                          className: "framer-1ljuacd",
                          "data-framer-name": "Action Button Text",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "XRvjtoyeM",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-5ba593c2-56ad-43ce-952c-f5cafa13d554, rgb(19, 115, 213))",
                            "--framer-paragraph-spacing": "0px",
                          },
                          verticalAlignment: "center",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsxs(motion.div, {
                          className: "framer-w7gppq",
                          "data-framer-name": "logo",
                          layoutDependency: layoutDependency,
                          layoutId: "PA07z1u0k",
                          style: {
                            borderBottomLeftRadius: 999,
                            borderBottomRightRadius: 999,
                            borderTopLeftRadius: 999,
                            borderTopRightRadius: 999,
                          },
                          children: [
                            /*#__PURE__*/ _jsx(Vector, {
                              animated: true,
                              className: "framer-10py6nu",
                              layoutDependency: layoutDependency,
                              layoutId: "szzIW5qdC",
                              style: { "--1ainiew": "rgb(20, 116, 214)" },
                            }),
                            /*#__PURE__*/ _jsx(Vector, {
                              animated: true,
                              className: "framer-6cdedz",
                              layoutDependency: layoutDependency,
                              layoutId: "v7SLbFYNi",
                              style: { "--1ainiew": "rgb(20, 116, 214)" },
                            }),
                          ],
                        }),
                      ],
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1ld73g5",
                  "data-framer-name": "Image Wrap",
                  layoutDependency: layoutDependency,
                  layoutId: "qWnvZSxOH",
                  style: {
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8,
                  },
                  children: /*#__PURE__*/ _jsx(Image1, {
                    background: {
                      alt: "",
                      fit: "fill",
                      intrinsicHeight: 776,
                      intrinsicWidth: 564,
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) + 24 + 0 + 0 + 0
                      ),
                      pixelHeight: 776,
                      pixelWidth: 564,
                      sizes: `max((${
                        componentViewport?.width || "100vw"
                      } - 72px) / 2, 1px)`,
                      ...toResponsiveImage(SLjMvjeE7),
                    },
                    className: "framer-1qf8cwg",
                    layoutDependency: layoutDependency,
                    layoutId: "djkuchc13",
                    style: {
                      borderBottomLeftRadius: 8,
                      borderBottomRightRadius: 8,
                      borderTopLeftRadius: 8,
                      borderTopRightRadius: 8,
                      scale: 1,
                    },
                    variants: { "FwXhQIxKg-hover": { scale: 1.1 } },
                    ...addPropertyOverrides(
                      {
                        XqwBjkShH: {
                          background: {
                            alt: "",
                            fit: "fill",
                            intrinsicHeight: 776,
                            intrinsicWidth: 564,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) + 24 + 0 + 0 + 0 + 0
                            ),
                            pixelHeight: 776,
                            pixelWidth: 564,
                            sizes: `max(${
                              componentViewport?.width || "100vw"
                            } - 48px, 1px)`,
                            ...toResponsiveImage(SLjMvjeE7),
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              ],
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-LZY9M.framer-ihkjhl, .framer-LZY9M .framer-ihkjhl { display: block; }",
  ".framer-LZY9M.framer-1a6prdx { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; text-decoration: none; width: 636px; }",
  ".framer-LZY9M .framer-17o43no { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-LZY9M .framer-1nj2sfk { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: auto; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-LZY9M .framer-plzkz6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-LZY9M .framer-12i2jbv, .framer-LZY9M .framer-15414dl, .framer-LZY9M .framer-1j7ou8j { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-LZY9M .framer-jw18uq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-LZY9M .framer-10nguj4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-LZY9M .framer-1ljuacd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-LZY9M .framer-w7gppq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: 16px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 16px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-LZY9M .framer-10py6nu { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 13px; }",
  ".framer-LZY9M .framer-6cdedz { aspect-ratio: 1 / 1; bottom: -14px; flex: none; height: auto; left: -14px; position: absolute; width: 13px; z-index: 1; }",
  ".framer-LZY9M .framer-1ld73g5 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-LZY9M .framer-1qf8cwg { aspect-ratio: 0.7268041237113402 / 1; flex: 1 0 0px; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-LZY9M.framer-v-1ip2hgu.framer-1a6prdx { cursor: unset; width: 390px; }",
  ".framer-LZY9M.framer-v-1ip2hgu .framer-17o43no { flex-direction: column; }",
  ".framer-LZY9M.framer-v-1ip2hgu .framer-1nj2sfk { align-self: unset; flex: none; gap: 40px; height: min-content; justify-content: center; order: 1; width: 100%; }",
  ".framer-LZY9M.framer-v-1ip2hgu .framer-plzkz6 { gap: 16px; }",
  ".framer-LZY9M.framer-v-1ip2hgu .framer-1ld73g5 { flex: none; order: 0; width: 100%; }",
  ".framer-LZY9M.framer-v-1ip2hgu .framer-1qf8cwg { aspect-ratio: 1.14 / 1; }",
  ".framer-LZY9M.framer-v-1a6prdx.hover .framer-10py6nu { position: absolute; right: -16px; top: -16px; z-index: 1; }",
  ".framer-LZY9M.framer-v-1a6prdx.hover .framer-6cdedz { bottom: unset; left: unset; position: relative; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 436
 * @framerIntrinsicWidth 636
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"XqwBjkShH":{"layout":["fixed","auto"]},"PPiHYqdgB":{"layout":["fixed","auto"]}}}
 * @framerVariables {"DLlH3YBTh":"title","goDSnHjCE":"subtitle","fbgHU7uFD":"text","SLjMvjeE7":"image","dgnFtzry_":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameroeEWvd_eU = withCSS(Component, css, "framer-LZY9M");
export default FrameroeEWvd_eU;
FrameroeEWvd_eU.displayName = "Blog Card";
FrameroeEWvd_eU.defaultProps = { height: 436, width: 636 };
addPropertyControls(FrameroeEWvd_eU, {
  variant: {
    options: ["FwXhQIxKg", "XqwBjkShH"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  DLlH3YBTh: {
    defaultValue: "Hygiene :",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onDLlH3YBThChange: { changes: "DLlH3YBTh", type: ControlType.ChangeHandler },
  goDSnHjCE: {
    defaultValue: "Simple Daily Habits for Better Oral Health",
    displayTextArea: false,
    title: "Subtitle",
    type: ControlType.String,
  },
  ongoDSnHjCEChange: { changes: "goDSnHjCE", type: ControlType.ChangeHandler },
  fbgHU7uFD: {
    defaultValue:
      "Brushing and flossing daily help keep teeth clean and gums healthy.",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  onfbgHU7uFDChange: { changes: "fbgHU7uFD", type: ControlType.ChangeHandler },
  SLjMvjeE7: {
    __defaultAssetReference:
      "data:framer/asset-reference,dfy1DIiq37YRVJKtqLtixXpzBk.png?originalFilename=Image+%2874%29.png&width=564&height=776",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,dfy1DIiq37YRVJKtqLtixXpzBk.png?originalFilename=Image+%2874%29.png&width=564&height=776",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  dgnFtzry_: { title: "Link", type: ControlType.Link },
});
addFonts(
  FrameroeEWvd_eU,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...VectorFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameroeEWvd_eU",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerVariables:
          '{"DLlH3YBTh":"title","goDSnHjCE":"subtitle","fbgHU7uFD":"text","SLjMvjeE7":"image","dgnFtzry_":"link"}',
        framerIntrinsicWidth: "636",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"XqwBjkShH":{"layout":["fixed","auto"]},"PPiHYqdgB":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "436",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./oeEWvd_eU.map
