// Generated by Framer (4f63079)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const otNFWPuoI = undefined;
const mask =
  'url(\'data:image/svg+xml,<svg display="block" id="3739010269" role="presentation" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M 10.5 5.332 C 11.167 5.717 11.167 6.679 10.5 7.064 L 1.5 12.26 C 0.833 12.645 0 12.164 0 11.394 L 0 1.001 C 0 0.232 0.833 -0.249 1.5 0.135 Z" fill="var(--1ainiew, rgb(20,116,214))" height="12.395309175534889px" id="BKQtK2WDP" transform="translate(4 1.802)" width="10.999987500000003px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ color, height, id, width, ...props }) => {
  return {
    ...props,
    otNFWPuoI: color ?? props.otNFWPuoI ?? "rgb(20, 116, 214)",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, otNFWPuoI, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-acNac", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--1ainiew": otNFWPuoI, ...style },
  });
});
const css = [
  `.framer-acNac { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--1ainiew); mask: ${mask}; width: 16px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 16
 * @framerIntrinsicHeight 16
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"otNFWPuoI":"color"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Polygon 1","color":{"type":"variable","value":"1ainiew"},"set":{"localId":"vectorSet/DLVYEDHxh","id":"DLVYEDHxh","moduleId":"H03uyQ6iKrzXYyHfcrbS"}}
 */ const Icon = withCSS(Component, css, "framer-acNac");
Icon.displayName = "Polygon 1";
export default Icon;
addPropertyControls(Icon, {
  otNFWPuoI: {
    defaultValue: "rgb(20, 116, 214)",
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerContractVersion: "1",
        framerIntrinsicWidth: "16",
        framerVariables: '{"otNFWPuoI":"color"}',
        framerVector:
          '{"name":"Polygon 1","color":{"type":"variable","value":"1ainiew"},"set":{"localId":"vectorSet/DLVYEDHxh","id":"DLVYEDHxh","moduleId":"H03uyQ6iKrzXYyHfcrbS"}}',
        framerIntrinsicHeight: "16",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
