// Generated by Framer (8a671e2)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle2 from "https://framerusercontent.com/modules/UqtXQCViTtsu1vbFZs4w/n0nA0mPhFzPRX0iY7cco/N_TgVO6x4.js";
import * as sharedStyle from "https://framerusercontent.com/modules/zbVJsUpTCk3xtafWDaCn/KykQNbYci2z39MdNYDX1/phrzN361W.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/L7uDWQ1qdoae3ApC0I25/wYJ7fs2YF7sw452xOg3N/s_6W4tJ6y.js";
const cycleOrder = ["nGXvgJogl", "fg3QBA0qL", "pUjSBiSKg"];
const serializationHash = "framer-TTsZL";
const variantClassNames = {
  fg3QBA0qL: "framer-v-1ji69to",
  nGXvgJogl: "framer-v-14r0h94",
  pUjSBiSKg: "framer-v-c6dxdy",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const Hc8eLiUtm = undefined;
const REnOKxfX5 = undefined;
const NjvQWfmKp = undefined;
const kRLAhuyTM = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Desktop v1": "nGXvgJogl",
  "desktop V2": "fg3QBA0qL",
  Phone: "pUjSBiSKg",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  height,
  id,
  image,
  serial,
  text,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    Hc8eLiUtm: serial ?? props.Hc8eLiUtm ?? "01.",
    kRLAhuyTM:
      text ??
      props.kRLAhuyTM ??
      "We use digital X-ray technology for accurate diagnosis and faster treatment planning.",
    NjvQWfmKp: title ?? props.NjvQWfmKp ?? "Advanced Digital X Ray Imaging",
    REnOKxfX5: image ??
      props.REnOKxfX5 ?? {
        alt: "",
        pixelHeight: 920,
        pixelWidth: 1096,
        src: "https://framerusercontent.com/images/20oEi8RnEwvEsZQN8XY6SIOu1c.png?width=1096&height=920",
        srcSet:
          "https://framerusercontent.com/images/20oEi8RnEwvEsZQN8XY6SIOu1c.png?scale-down-to=512&width=1096&height=920 512w,https://framerusercontent.com/images/20oEi8RnEwvEsZQN8XY6SIOu1c.png?scale-down-to=1024&width=1096&height=920 1024w,https://framerusercontent.com/images/20oEi8RnEwvEsZQN8XY6SIOu1c.png?width=1096&height=920 1096w",
      },
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "nGXvgJogl",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    Hc8eLiUtm,
    REnOKxfX5,
    NjvQWfmKp,
    kRLAhuyTM,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "nGXvgJogl",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-14r0h94",
            className,
            classNames
          ),
          "data-framer-name": "Desktop v1",
          layoutDependency: layoutDependency,
          layoutId: "nGXvgJogl",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              fg3QBA0qL: { "data-framer-name": "desktop V2" },
              pUjSBiSKg: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-qu6aw6",
              "data-framer-name": "Feature Item Container",
              layoutDependency: layoutDependency,
              layoutId: "cM1i0DYkV",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-ne5fgw",
                      "data-styles-preset": "phrzN361W",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                      },
                      children: "01.",
                    }),
                  }),
                  className: "framer-1o4iuk5",
                  "data-framer-name": "Feature Number",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "vWV0CXrZJ",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: Hc8eLiUtm,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0
                    ),
                    pixelHeight: 920,
                    pixelWidth: 1096,
                    ...toResponsiveImage(REnOKxfX5),
                  },
                  className: "framer-10o2ux7",
                  "data-framer-name": "Feature Image",
                  fitImageDimension: "height",
                  layoutDependency: layoutDependency,
                  layoutId: "fPfEcDhrQ",
                  style: {
                    borderBottomLeftRadius: 16,
                    borderBottomRightRadius: 16,
                    borderTopLeftRadius: 16,
                    borderTopRightRadius: 16,
                  },
                  ...addPropertyOverrides(
                    {
                      pUjSBiSKg: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 0 + 0 + 0 + 0
                          ),
                          pixelHeight: 920,
                          pixelWidth: 1096,
                          sizes: componentViewport?.width || "100vw",
                          ...toResponsiveImage(REnOKxfX5),
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1c5o6s8",
              "data-framer-name": "Feature Description Container",
              layoutDependency: layoutDependency,
              layoutId: "qwehXNnuc",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-o8h2hh",
                      "data-styles-preset": "s_6W4tJ6y",
                      dir: "auto",
                      style: {
                        "--framer-text-alignment": "left",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50)))",
                      },
                      children: "Advanced Digital X Ray Imaging",
                    }),
                  }),
                  className: "framer-1irhgz4",
                  "data-framer-name": "Feature Title",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "YDMRrAq5X",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: NjvQWfmKp,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-9usbxk",
                  "data-framer-name": "Text Wrapper",
                  layoutDependency: layoutDependency,
                  layoutId: "bwrB8Cg6O",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-1izoxyw",
                        "data-styles-preset": "N_TgVO6x4",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113)))",
                        },
                        children:
                          "We use digital X-ray technology for accurate diagnosis and faster treatment planning.",
                      }),
                    }),
                    className: "framer-muhmrx",
                    "data-framer-name": "Feature Details",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "Z4ArDvIu1",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-1c7bb858-e55b-41f4-8f47-7bf0b11792f5, rgb(96, 98, 113))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: kRLAhuyTM,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-TTsZL.framer-g9xk0, .framer-TTsZL .framer-g9xk0 { display: block; }",
  ".framer-TTsZL.framer-14r0h94 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1140px; }",
  ".framer-TTsZL .framer-qu6aw6 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 494px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-TTsZL .framer-1o4iuk5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-TTsZL .framer-10o2ux7 { flex: 1 0 0px; height: auto; max-width: 274px; position: relative; width: 1px; }",
  ".framer-TTsZL .framer-1c5o6s8 { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: auto; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-TTsZL .framer-1irhgz4 { flex: 1 0 0px; height: auto; max-width: 320px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-TTsZL .framer-9usbxk { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; max-width: 330px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-TTsZL .framer-muhmrx { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-TTsZL.framer-v-1ji69to .framer-1o4iuk5, .framer-TTsZL.framer-v-c6dxdy .framer-1o4iuk5 { order: 1; }",
  ".framer-TTsZL.framer-v-1ji69to .framer-10o2ux7 { order: 0; }",
  ".framer-TTsZL.framer-v-c6dxdy.framer-14r0h94 { flex-direction: column; gap: 16px; width: 390px; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-qu6aw6 { flex: none; flex-direction: column; gap: 16px; justify-content: center; max-width: unset; width: 100%; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-10o2ux7 { flex: none; max-width: unset; order: 0; width: 100%; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-1c5o6s8 { align-self: unset; flex: none; flex-direction: column; gap: 16px; height: min-content; justify-content: center; width: 100%; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-1irhgz4 { flex: none; max-width: unset; width: 100%; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-9usbxk { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; height: min-content; max-width: unset; width: 100%; }",
  ".framer-TTsZL.framer-v-c6dxdy .framer-muhmrx { flex: none; max-width: 330px; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 230
 * @framerIntrinsicWidth 1140
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"fg3QBA0qL":{"layout":["fixed","auto"]},"pUjSBiSKg":{"layout":["fixed","auto"]}}}
 * @framerVariables {"Hc8eLiUtm":"serial","REnOKxfX5":"image","NjvQWfmKp":"title","kRLAhuyTM":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerzxo8Mi0lE = withCSS(Component, css, "framer-TTsZL");
export default Framerzxo8Mi0lE;
Framerzxo8Mi0lE.displayName = "Technoogy Card";
Framerzxo8Mi0lE.defaultProps = { height: 230, width: 1140 };
addPropertyControls(Framerzxo8Mi0lE, {
  variant: {
    options: ["nGXvgJogl", "fg3QBA0qL", "pUjSBiSKg"],
    optionTitles: ["Desktop v1", "desktop V2", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  Hc8eLiUtm: {
    defaultValue: "01.",
    displayTextArea: false,
    title: "Serial",
    type: ControlType.String,
  },
  onHc8eLiUtmChange: { changes: "Hc8eLiUtm", type: ControlType.ChangeHandler },
  REnOKxfX5: {
    __defaultAssetReference:
      "data:framer/asset-reference,20oEi8RnEwvEsZQN8XY6SIOu1c.png?width=1096&height=920",
    __vekterDefault: {
      alt: "",
      assetReference:
        "data:framer/asset-reference,20oEi8RnEwvEsZQN8XY6SIOu1c.png?width=1096&height=920",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  NjvQWfmKp: {
    defaultValue: "Advanced Digital X Ray Imaging",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onNjvQWfmKpChange: { changes: "NjvQWfmKp", type: ControlType.ChangeHandler },
  kRLAhuyTM: {
    defaultValue:
      "We use digital X-ray technology for accurate diagnosis and faster treatment planning.",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  onkRLAhuyTMChange: { changes: "kRLAhuyTM", type: ControlType.ChangeHandler },
});
addFonts(
  Framerzxo8Mi0lE,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerzxo8Mi0lE",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "230",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"fg3QBA0qL":{"layout":["fixed","auto"]},"pUjSBiSKg":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1140",
        framerContractVersion: "1",
        framerVariables:
          '{"Hc8eLiUtm":"serial","REnOKxfX5":"image","NjvQWfmKp":"title","kRLAhuyTM":"text"}',
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./zxo8Mi0lE.map
