// Generated by Framer (835d061)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  Image as Image1,
  PathVariablesContext,
  PropertyOverrides,
  queryCache,
  ResolveLinks,
  RichText,
  runTasksWithYield,
  runWithYield,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  useRouteElementId,
  useRouter,
  useSiteRefs,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ServiceContainer from "#framer/local/canvasComponent/czSxpE1kn/czSxpE1kn.js";
import SectionTag from "#framer/local/canvasComponent/F2GdECUJ5/F2GdECUJ5.js";
import Service from "#framer/local/collection/QSkWLVmAe/QSkWLVmAe.js";
import * as sharedStyle from "#framer/local/css/K6baPjkRU/K6baPjkRU.js";
import * as sharedStyle1 from "#framer/local/css/v2nyWdiax/v2nyWdiax.js";
import metadataProvider from "#framer/local/webPageMetadata/QQGVgSF_N/QQGVgSF_N.js";
const SectionTagFonts = getFonts(SectionTag);
const MotionDivWithOptimizedAppearEffect = withOptimizedAppearEffect(
  motion.div
);
const MotionDivWithFX = withFX(motion.div);
const ServiceContainerFonts = getFonts(ServiceContainer);
const ContainerWithFX = withFX(Container);
const breakpoints = {
  GGJ46uRMx: "(max-width: 809.98px)",
  rI81MzUfX: "(min-width: 1200px)",
  SMOcbbEgq: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-Om31z";
const variantClassNames = {
  GGJ46uRMx: "framer-v-108084x",
  rI81MzUfX: "framer-v-via7dw",
  SMOcbbEgq: "framer-v-1to3i6w",
};
const repeater_item_indexCpNe3Uwr3 = undefined;
const crLSDaHfcCpNe3Uwr3 = undefined;
const LHymIic53CpNe3Uwr3 = undefined;
const jmVdwWaeqCpNe3Uwr3 = undefined;
const SfYYZUpliCpNe3Uwr3 = undefined;
const Xp0UqGBJACpNe3Uwr3 = undefined;
const idCpNe3Uwr3 = undefined;
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const transition1 = {
  delay: 0,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 20,
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 24,
};
const transition2 = {
  delay: 0.2,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation3 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 24,
};
const toString = (value) => {
  return typeof value === "string" ? value : String(value);
};
const prefix = (value, prefix) => {
  if (typeof value === "string" && typeof prefix === "string") {
    return prefix + value;
  } else if (typeof value === "string") {
    return value;
  } else if (typeof prefix === "string") {
    return prefix;
  }
  return "";
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const query = () => ({
  from: { alias: "CpNe3Uwr3", data: Service, type: "Collection" },
  select: [
    { collection: "CpNe3Uwr3", name: "crLSDaHfc", type: "Identifier" },
    { collection: "CpNe3Uwr3", name: "LHymIic53", type: "Identifier" },
    { collection: "CpNe3Uwr3", name: "jmVdwWaeq", type: "Identifier" },
    { collection: "CpNe3Uwr3", name: "SfYYZUpli", type: "Identifier" },
    { collection: "CpNe3Uwr3", name: "Xp0UqGBJA", type: "Identifier" },
    { collection: "CpNe3Uwr3", name: "id", type: "Identifier" },
  ],
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const humanReadableVariantMap = {
  Desktop: "rI81MzUfX",
  Phone: "GGJ46uRMx",
  Tablet: "SMOcbbEgq",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "rI81MzUfX",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const elementId = useRouteElementId("G_L4Waqzj");
  const dynamicRef = useSiteRefs();
  const isDisplayed = () => {
    if (!isBrowser()) return true;
    if (baseVariant === "GGJ46uRMx") return false;
    return true;
  };
  const router = useRouter();
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "rI81MzUfX",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-via7dw", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-nv5xy7",
              "data-framer-name": "Hero Section",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsx(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 1032,
                    intrinsicWidth: 1600,
                    pixelHeight: 1032,
                    pixelWidth: 1600,
                    sizes: componentViewport?.width || "100vw",
                    src: "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032",
                    srcSet:
                      "https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=512&width=1600&height=1032 512w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?scale-down-to=1024&width=1600&height=1032 1024w,https://framerusercontent.com/images/i1O8gTzTaKkgnfU2RRcaMdxA.png?width=1600&height=1032 1600w",
                  },
                  className: "framer-14jeybn",
                  "data-framer-name": "BG",
                }),
                /*#__PURE__*/ _jsx("div", { className: "framer-k5sl7r" }),
                /*#__PURE__*/ _jsxs(MotionDivWithOptimizedAppearEffect, {
                  animate: animation,
                  className: "framer-1boub1w",
                  "data-framer-appear-id": "1boub1w",
                  "data-framer-name": "Container",
                  id: elementId,
                  initial: animation1,
                  optimized: true,
                  ref: dynamicRef(elementId),
                  children: [
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 47,
                      children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-e7tj2x-container",
                        nodeId: "tea2Adm39",
                        scopeId: "QQGVgSF_N",
                        children: /*#__PURE__*/ _jsx(SectionTag, {
                          height: "100%",
                          id: "tea2Adm39",
                          j9h2sFaQp: "Our Services",
                          layoutId: "tea2Adm39",
                          qbRh5Zv2v:
                            "var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, rgb(250, 249, 255))",
                          width: "100%",
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                      className: "framer-feq2k6",
                      "data-framer-name": "Text",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h1", {
                              className: "framer-styles-preset-18tf0iw",
                              "data-styles-preset": "K6baPjkRU",
                              dir: "auto",
                              style: {
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              },
                              children: "Meet",
                            }),
                          }),
                          className: "framer-152nyyu",
                          "data-framer-name": "Hero Title",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h1", {
                              className: "framer-styles-preset-1h8c9zs",
                              "data-styles-preset": "v2nyWdiax",
                              dir: "auto",
                              style: {
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              },
                              children: /*#__PURE__*/ _jsx("em", {
                                children: "Our Experienced and",
                              }),
                            }),
                          }),
                          className: "framer-r1pot9",
                          "data-framer-name": "Hero Title",
                          fonts: ["Inter", "Inter-Italic"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h1", {
                              className: "framer-styles-preset-1h8c9zs",
                              "data-styles-preset": "v2nyWdiax",
                              dir: "auto",
                              style: {
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              },
                              children: /*#__PURE__*/ _jsx("em", {
                                children: "Caring",
                              }),
                            }),
                          }),
                          className: "framer-16qm5po",
                          "data-framer-name": "Hero Title",
                          fonts: ["Inter", "Inter-Italic"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx("h1", {
                              className: "framer-styles-preset-18tf0iw",
                              "data-styles-preset": "K6baPjkRU",
                              dir: "auto",
                              style: {
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--token-7327e233-475e-4754-a6df-d8e7457f7f40, rgb(10, 15, 50))",
                              },
                              children: "Dental Team",
                            }),
                          }),
                          className: "framer-ghmxqo",
                          "data-framer-name": "Hero Title",
                          fonts: ["Inter"],
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-3pvdgb",
              "data-framer-name": "Services",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsxs("div", {
                className: "framer-1gbbk9f",
                "data-framer-name": "Container",
                children: [
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(MotionDivWithFX, {
                      __framer__animate: { transition: transition2 },
                      __framer__animateOnce: true,
                      __framer__enter: animation2,
                      __framer__exit: animation3,
                      __framer__styleAppearEffectEnabled: true,
                      __framer__threshold: 0,
                      __perspectiveFX: false,
                      __targetOpacity: 1,
                      className: "framer-aes6zj hidden-108084x",
                      "data-framer-name": "Line",
                    }),
                  /*#__PURE__*/ _jsx("div", {
                    className: "framer-f4w3el",
                    children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                      children: /*#__PURE__*/ _jsx(QueryData, {
                        query: query(),
                        children: (collection, paginationInfo, loadMore) => {
                          return /*#__PURE__*/ _jsx(_Fragment, {
                            children: collection?.map(
                              (
                                {
                                  crLSDaHfc: crLSDaHfcCpNe3Uwr3,
                                  id: idCpNe3Uwr3,
                                  jmVdwWaeq: jmVdwWaeqCpNe3Uwr3,
                                  LHymIic53: LHymIic53CpNe3Uwr3,
                                  SfYYZUpli: SfYYZUpliCpNe3Uwr3,
                                  Xp0UqGBJA: Xp0UqGBJACpNe3Uwr3,
                                },
                                index
                              ) => {
                                crLSDaHfcCpNe3Uwr3 ??= "";
                                LHymIic53CpNe3Uwr3 ??= "";
                                Xp0UqGBJACpNe3Uwr3 ??= "";
                                const repeater_item_indexCpNe3Uwr3 = index + 1;
                                return /*#__PURE__*/ _jsx(
                                  LayoutGroup,
                                  {
                                    id: `CpNe3Uwr3-${idCpNe3Uwr3}`,
                                    children: /*#__PURE__*/ _jsx(
                                      PathVariablesContext.Provider,
                                      {
                                        value: {
                                          Xp0UqGBJA: Xp0UqGBJACpNe3Uwr3,
                                        },
                                        children: /*#__PURE__*/ _jsx("div", {
                                          className: "framer-b8usq3",
                                          children: /*#__PURE__*/ _jsx(
                                            ResolveLinks,
                                            {
                                              links: [
                                                {
                                                  href: {
                                                    pathVariables: {
                                                      Xp0UqGBJA:
                                                        Xp0UqGBJACpNe3Uwr3,
                                                    },
                                                    webPageId: "x5GdRXF3b",
                                                  },
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                                {
                                                  href: {
                                                    pathVariables: {
                                                      Xp0UqGBJA:
                                                        Xp0UqGBJACpNe3Uwr3,
                                                    },
                                                    webPageId: "x5GdRXF3b",
                                                  },
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                                {
                                                  href: {
                                                    pathVariables: {
                                                      Xp0UqGBJA:
                                                        Xp0UqGBJACpNe3Uwr3,
                                                    },
                                                    webPageId: "x5GdRXF3b",
                                                  },
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                              ],
                                              children: (resolvedLinks) =>
                                                /*#__PURE__*/ _jsx(
                                                  PropertyOverrides,
                                                  {
                                                    breakpoint: baseVariant,
                                                    overrides: {
                                                      GGJ46uRMx: {
                                                        width: `max(min(max(${
                                                          componentViewport?.width ||
                                                          "100vw"
                                                        } - 40px, 1px), 1296px), 1px)`,
                                                      },
                                                    },
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        ComponentViewportProvider,
                                                        {
                                                          height: 268,
                                                          width: `max(min(max(${
                                                            componentViewport?.width ||
                                                            "100vw"
                                                          } - 60px, 1px), 1296px), 1px)`,
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ContainerWithFX,
                                                              {
                                                                __framer__animate:
                                                                  {
                                                                    transition:
                                                                      transition2,
                                                                  },
                                                                __framer__animateOnce: true,
                                                                __framer__enter:
                                                                  animation2,
                                                                __framer__exit:
                                                                  animation3,
                                                                __framer__styleAppearEffectEnabled: true,
                                                                __framer__threshold: 0,
                                                                __perspectiveFX: false,
                                                                __targetOpacity: 1,
                                                                className:
                                                                  "framer-y8mum4-container",
                                                                nodeId:
                                                                  "ETAxpqDd4",
                                                                rendersWithMotion: true,
                                                                scopeId:
                                                                  "QQGVgSF_N",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    PropertyOverrides,
                                                                    {
                                                                      breakpoint:
                                                                        baseVariant,
                                                                      overrides:
                                                                        {
                                                                          GGJ46uRMx:
                                                                            {
                                                                              OEycECYO5:
                                                                                resolvedLinks[2],
                                                                              variant:
                                                                                matchVariant(
                                                                                  "x1LMBp0zJ"
                                                                                ),
                                                                            },
                                                                          SMOcbbEgq:
                                                                            {
                                                                              OEycECYO5:
                                                                                resolvedLinks[1],
                                                                              variant:
                                                                                matchVariant(
                                                                                  "lkBc2Yrwr"
                                                                                ),
                                                                            },
                                                                        },
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          ServiceContainer,
                                                                          {
                                                                            cjVrZJHtD:
                                                                              LHymIic53CpNe3Uwr3,
                                                                            height:
                                                                              "100%",
                                                                            id: "ETAxpqDd4",
                                                                            kEvnWRt9L:
                                                                              toResponsiveImage(
                                                                                jmVdwWaeqCpNe3Uwr3
                                                                              ),
                                                                            layoutId:
                                                                              "ETAxpqDd4",
                                                                            OEycECYO5:
                                                                              resolvedLinks[0],
                                                                            qUGb3yn_N:
                                                                              crLSDaHfcCpNe3Uwr3,
                                                                            style:
                                                                              {
                                                                                width:
                                                                                  "100%",
                                                                              },
                                                                            sWhPTYRj3:
                                                                              prefix(
                                                                                toString(
                                                                                  repeater_item_indexCpNe3Uwr3
                                                                                ),
                                                                                "0"
                                                                              ),
                                                                            variant:
                                                                              matchVariant(
                                                                                "gBtM2Atjg"
                                                                              ),
                                                                            width:
                                                                              "100%",
                                                                            X7_QVo0Gv:
                                                                              toResponsiveImage(
                                                                                SfYYZUpliCpNe3Uwr3
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                            }
                                          ),
                                        }),
                                      }
                                    ),
                                  },
                                  idCpNe3Uwr3
                                );
                              }
                            ),
                          });
                        },
                      }),
                    }),
                  }),
                ],
              }),
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  ".framer-Om31z.framer-jz1aqz, .framer-Om31z .framer-jz1aqz { display: block; }",
  ".framer-Om31z.framer-via7dw { align-content: center; align-items: center; background-color: var(--token-a8b96332-4abd-4af4-ad85-c183d66adf19, #faf9ff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-Om31z .framer-nv5xy7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 210px 30px 0px 30px; position: relative; width: 100%; z-index: 1; }",
  ".framer-Om31z .framer-14jeybn { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; justify-content: center; left: 0px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-filter-override, filter); }",
  ".framer-Om31z .framer-k5sl7r { background: linear-gradient(180deg, var(--token-b792d557-4853-49ac-865a-1d8073a4ab4e, rgba(174, 220, 253, 0.6)) 0%, rgba(251, 250, 255, 0) 100%); bottom: 0px; flex: none; gap: 40px; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 100%; }",
  ".framer-Om31z .framer-1boub1w { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1296px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-Om31z .framer-e7tj2x-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-Om31z .framer-feq2k6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 10px; height: min-content; justify-content: flex-start; max-width: 992px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-Om31z .framer-152nyyu, .framer-Om31z .framer-r1pot9, .framer-Om31z .framer-16qm5po, .framer-Om31z .framer-ghmxqo { --framer-paragraph-spacing: 0px; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Om31z .framer-3pvdgb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 72px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 160px 30px 160px 30px; position: relative; width: 100%; }",
  ".framer-Om31z .framer-1gbbk9f { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; max-width: 1296px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-Om31z .framer-aes6zj { background-color: var(--token-5e421d18-5d17-4869-827f-e8cec0385dad, rgba(10, 15, 50, 0.2)); flex: none; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
  ".framer-Om31z .framer-f4w3el { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
  ".framer-Om31z .framer-b8usq3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
  ".framer-Om31z .framer-y8mum4-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-Om31z.framer-via7dw { width: 810px; } .framer-Om31z .framer-nv5xy7 { padding: 150px 30px 0px 30px; } .framer-Om31z .framer-152nyyu, .framer-Om31z .framer-r1pot9, .framer-Om31z .framer-16qm5po, .framer-Om31z .framer-ghmxqo { max-width: 550px; white-space: pre-wrap; word-break: break-word; word-wrap: break-word; } .framer-Om31z .framer-3pvdgb { padding: 80px 30px 80px 30px; } .framer-Om31z .framer-f4w3el { gap: 32px; }}",
  "@media (max-width: 809.98px) { .framer-Om31z.framer-via7dw { width: 390px; } .framer-Om31z .framer-nv5xy7 { gap: 40px; padding: 120px 20px 0px 20px; } .framer-Om31z .framer-1boub1w { align-content: center; align-items: center; } .framer-Om31z .framer-feq2k6 { gap: 0px 6px; justify-content: center; } .framer-Om31z .framer-3pvdgb { padding: 60px 20px 60px 20px; } .framer-Om31z .framer-f4w3el { gap: 24px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 4006
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SMOcbbEgq":{"layout":["fixed","auto"]},"GGJ46uRMx":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"G_L4Waqzj":{"pattern":":G_L4Waqzj","name":"nav"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerQQGVgSF_N = withCSS(Component, css, "framer-Om31z");
export default FramerQQGVgSF_N;
FramerQQGVgSF_N.displayName = "Page";
FramerQQGVgSF_N.defaultProps = { height: 4006, width: 1200 };
addFonts(
  FramerQQGVgSF_N,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "italic",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
          weight: "400",
        },
      ],
    },
    ...SectionTagFonts,
    ...ServiceContainerFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerQQGVgSF_N.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const priority = context.priority;
    const queryCacheEntry = queryCache.get(query(), locale, priority);
    return runTasksWithYield(
      [
        () => queryCacheEntry.preload(),
        () => forwardLoader(SectionTag, {}, context),
        async () => {
          const parentData =
            (await runWithYield(
              () => queryCacheEntry.readMaybeAsync(),
              context
            )) ?? [];
          return runTasksWithYield(
            parentData.flatMap(
              (item) => () => forwardLoader(ServiceContainer, {}, context)
            ),
            context
          );
        },
      ],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerQQGVgSF_N",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerLayoutTemplateFlowEffect: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerScrollSections:
          '{"G_L4Waqzj":{"pattern":":G_L4Waqzj","name":"nav"}}',
        framerResponsiveScreen: "true",
        framerIntrinsicHeight: "4006",
        framerIntrinsicWidth: "1200",
        framerAcceptsLayoutTemplate: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SMOcbbEgq":{"layout":["fixed","auto"]},"GGJ46uRMx":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
